export const integrations = [
  // Git providers
  {
    name: 'GitHub',
    category: 'git',
    icon: '/img/guides/icons/GitHub.svg',
    darkIcon: '/img/guides/icons/dark/GitHub.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/github',
  },
  {
    name: 'GitLab',
    category: 'git',
    icon: '/img/guides/icons/GitLab.svg',
    darkIcon: '/img/guides/icons/dark/GitLab.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/gitlab',
  },
  {
    name: 'BitBucket',
    category: 'git',
    icon: '/img/guides/icons/BitBucket.svg',
    darkIcon: '/img/guides/icons/dark/BitBucket.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/bitbucket',
  },
  {
    name: 'AzureDevops',
    category: 'git',
    icon: '/img/guides/icons/AzureDevops.svg',
    darkIcon: '/img/guides/icons/dark/AzureDevops.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/azure-devops',
  },
  // CI/CD
  {
    name: 'Jenkins',
    category: 'cicd',
    icon: '/img/guides/icons/Jenkins.svg',
    darkIcon: '/img/guides/icons/dark/Jenkins.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins',
  },
  {
    name: 'Octopus Deploy',
    category: 'cicd',
    icon: '/img/guides/icons/OctopusDeploy.svg',
    darkIcon: '/img/guides/icons/dark/OctopusDeploy.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy',
  },
  {
    name: 'ArgoCD',
    category: 'kubernetes',
    icon: '/img/guides/icons/ArgoCD.svg',
    darkIcon: '/img/guides/icons/dark/ArgoCD.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/argocd',
  },
  // Project Management
  {
    name: 'Jira',
    category: 'project',
    icon: '/img/guides/icons/Jira.svg',
    darkIcon: '/img/guides/icons/dark/Jira.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/project-management/jira',
  },
  {
    name: 'Linear',
    category: 'project',
    icon: '/img/guides/icons/Linear.svg',
    darkIcon: '/img/guides/icons/dark/Linear.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/project-management/linear',
  },
  // Infrastructure
  {
    name: 'Kubernetes',
    category: 'kubernetes',
    icon: '/img/guides/icons/Kubernetes.svg',
    darkIcon: '/img/guides/icons/dark/Kubernetes.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/kubernetes',
  },
  {
    name: 'AWS',
    category: 'cloud-providers',
    icon: '/img/guides/icons/AWS.svg',
    darkIcon: '/img/guides/icons/dark/AWS.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws',
  },
  {
    name: 'Azure',
    category: 'cloud-providers',
    icon: '/img/guides/icons/Azure.svg',
    darkIcon: '/img/guides/icons/dark/Azure.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure',
  },
  {
    name: 'GCP',
    category: 'cloud-providers',
    icon: '/img/guides/icons/GCP.svg',
    darkIcon: '/img/guides/icons/dark/GCP.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp',
  },
  {
    name: 'Terraform',
    category: 'iac',
    icon: '/img/guides/icons/Terraform.svg',
    darkIcon: '/img/guides/icons/dark/Terraform.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/terraform-cloud',
  },
  // Monitoring & APM
  {
    name: 'Datadog',
    category: 'monitoring',
    icon: '/img/guides/icons/Datadog.svg',
    darkIcon: '/img/guides/icons/dark/Datadog.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog',
  },
  {
    name: 'New Relic',
    category: 'monitoring',
    icon: '/img/guides/icons/NewRelic.svg',
    darkIcon: '/img/guides/icons/dark/NewRelic.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic',
  },
  {
    name: 'Sentry',
    category: 'monitoring',
    icon: '/img/guides/icons/Sentry.svg',
    darkIcon: '/img/guides/icons/dark/Sentry.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry',
  },
  // Security & Quality
  {
    name: 'Snyk',
    category: 'security',
    icon: '/img/guides/icons/Snyk.svg',
    darkIcon: '/img/guides/icons/dark/Snyk.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk',
  },
  {
    name: 'Wiz',
    category: 'security',
    icon: '/img/guides/icons/Wiz.svg',
    darkIcon: '/img/guides/icons/dark/Wiz.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz',
  },
  {
    name: 'SonarQube',
    category: 'security',
    icon: '/img/guides/icons/SonarQube.svg',
    darkIcon: '/img/guides/icons/dark/SonarQube.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube',
  },
  // Feature Management
  {
    name: 'Launchdarkly',
    category: 'feature',
    icon: '/img/guides/icons/Launchdarkly.svg',
    darkIcon: '/img/guides/icons/dark/Launchdarkly.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly',
  },
  // Incident Management
  {
    name: 'PagerDuty',
    category: 'incident',
    icon: '/img/guides/icons/PagerDuty.svg',
    darkIcon: '/img/guides/icons/dark/PagerDuty.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty',
  },
  {
    name: 'StatusPage',
    category: 'incident',
    icon: '/img/guides/icons/StatusPage.svg',
    darkIcon: '/img/guides/icons/dark/StatusPage.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage',
  },
  {
    name: 'FireHydrant',
    category: 'incident',
    icon: '/img/guides/icons/FireHydrant.svg',
    darkIcon: '/img/guides/icons/dark/FireHydrant.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant',
  },
  {
    name: 'OpsGenie',
    category: 'incident',
    icon: '/img/guides/icons/OpsGenie.svg',
    darkIcon: '/img/guides/icons/dark/OpsGenie.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie',
  },
  {
    name: 'ServiceNow',
    category: 'incident',
    icon: '/img/guides/icons/ServiceNow.svg',
    darkIcon: '/img/guides/icons/dark/ServiceNow.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow',
  },
  {
    name: 'Dynatrace',
    category: 'monitoring',
    icon: '/img/guides/icons/Dynatrace.svg',
    darkIcon: '/img/guides/icons/dark/Dynatrace.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace',
  },
  // Cloud Cost
  {
    name: 'Kubecost',
    category: 'cost',
    icon: '/img/guides/icons/Kubecost.svg',
    darkIcon: '/img/guides/icons/dark/Kubecost.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost',
  },
  {
    name: 'Opencost',
    category: 'cost',
    icon: '/img/guides/icons/Opencost.svg',
    darkIcon: '/img/guides/icons/dark/Opencost.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost',
  },
  {
    name: 'Kafka',
    category: 'event',
    icon: '/img/guides/icons/Kafka.svg',
    darkIcon: '/img/guides/icons/dark/Kafka.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka',
  },
  {
    name: 'Amplication',
    category: 'other',
    icon: '/img/guides/icons/Amplication.svg',
    darkIcon: '/img/guides/icons/dark/Amplication.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/other/amplication',
  },
  {
    name: 'Backstage',
    category: 'other',
    icon: '/img/guides/icons/Backstage.svg',
    darkIcon: '/img/guides/icons/dark/Backstage.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/other/backstage',
  }
];

export const categories = {
  'All': 'all',
  'Git': 'git',
  'Kubernetes': 'kubernetes',
  'Cloud providers': 'cloud-providers',
  'IaC': 'iac',
  'Incident management': 'incident',
  'Project management': 'project',
  'Code quality & security': 'security',
  'Feature management': 'feature',
  'APM & alerting': 'monitoring',
  'Cloud cost': 'cost',
  'Event processing': 'event',
  'CI/CD': 'cicd',
  'Other': 'other',
}; 