export const integrations = [
  // Git providers
  {
    name: 'GitHub',
    category: 'git',
    icon: '/img/guides/icons/GitHub.svg',
    darkIcon: '/img/guides/icons/dark/GitHub.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/github',
  },
  {
    name: 'GitLab',
    category: 'git',
    icon: '/img/guides/icons/GitLab.svg',
    darkIcon: '/img/guides/icons/dark/GitLab.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/gitlab',
  },
  {
    name: 'BitBucket',
    category: 'git',
    icon: '/img/guides/icons/BitBucket.svg',
    darkIcon: '/img/guides/icons/dark/BitBucket.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-cloud',
  },
  {
    name: 'BitBucket server integration',
    category: 'git',
    iconName: 'BitBucket',
    icon: '/img/guides/icons/BitBucket.svg',
    darkIcon: '/img/guides/icons/dark/BitBucket.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server',
  },
  {
    name: 'AzureDevops',
    category: 'git',
    icon: '/img/guides/icons/AzureDevops.svg',
    darkIcon: '/img/guides/icons/dark/AzureDevops.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/git/azure-devops',
  },
  // CI/CD
  {
    name: 'Jenkins',
    category: 'cicd',
    icon: '/img/guides/icons/Jenkins.svg',
    darkIcon: '/img/guides/icons/dark/Jenkins.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins',
  },
  {
    name: 'Octopus Deploy',
    category: 'cicd',
    icon: '/img/guides/icons/OctopusDeploy.svg',
    darkIcon: '/img/guides/icons/dark/OctopusDeploy.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy',
  },
  {
    name: 'ArgoCD',
    category: 'kubernetes',
    icon: '/img/guides/icons/ArgoCD.svg',
    darkIcon: '/img/guides/icons/dark/ArgoCD.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/argocd',
  },
  {
    name: 'Komodor',
    category: 'kubernetes',
    icon: '/img/guides/icons/Komodor.svg',
    darkIcon: '/img/guides/icons/dark/Komodor.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/komodor',
  },
  {
    name: 'Istio',
    category: 'kubernetes',
    icon: '/img/guides/icons/Istio.svg',
    darkIcon: '/img/guides/icons/dark/Istio.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/kubernetes/templates/istio',
  },
  // Project Management
  {
    name: 'Jira',
    category: 'project',
    iconName: 'Jira',
    icon: '/img/guides/icons/Jira.svg',
    darkIcon: '/img/guides/icons/dark/Jira.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/project-management/jira',
  },
  {
    name: 'Jira server (self-hosted)',
    category: 'project',
    iconName: 'Jira',
    icon: '/img/guides/icons/Jira.svg',
    darkIcon: '/img/guides/icons/dark/Jira.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/project-management/jira',
  },
  {
    name: 'Linear',
    category: 'project',
    icon: '/img/guides/icons/Linear.svg',
    darkIcon: '/img/guides/icons/dark/Linear.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/project-management/linear',
  },
  // Infrastructure
  {
    name: 'Kubernetes',
    category: 'kubernetes',
    icon: '/img/guides/icons/Kubernetes.svg',
    darkIcon: '/img/guides/icons/dark/Kubernetes.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/kubernetes',
  },
  {
    name: 'AWS self-hosted',
    category: 'cloud-providers',
    iconName: 'AWS',
    icon: '/img/guides/icons/AWS.svg',
    darkIcon: '/img/guides/icons/dark/AWS.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws',
  },
  {
    name: 'AWS hosted by Port',
    category: 'cloud-providers',
    iconName: 'AWS',
    icon: '/img/guides/icons/AWS.svg',
    darkIcon: '/img/guides/icons/dark/AWS.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws-v3/Overview',
  },
  {
    name: 'Azure',
    category: 'cloud-providers',
    icon: '/img/guides/icons/Azure.svg',
    darkIcon: '/img/guides/icons/dark/Azure.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure',
  },
  {
    name: 'GCP',
    category: 'cloud-providers',
    icon: '/img/guides/icons/GCP.svg',
    darkIcon: '/img/guides/icons/dark/GCP.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp',
  },
  {
    name: 'Terraform',
    category: 'iac',
    icon: '/img/guides/icons/Terraform.svg',
    darkIcon: '/img/guides/icons/dark/Terraform.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/terraform-cloud',
  },
  // Monitoring & APM
  {
    name: 'Datadog',
    category: 'monitoring',
    icon: '/img/guides/icons/Datadog.svg',
    darkIcon: '/img/guides/icons/dark/Datadog.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog',
  },
  {
    name: 'New Relic',
    category: 'monitoring',
    icon: '/img/guides/icons/NewRelic.svg',
    darkIcon: '/img/guides/icons/dark/NewRelic.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic',
  },
  {
    name: 'Sentry',
    category: 'monitoring',
    icon: '/img/guides/icons/Sentry.svg',
    darkIcon: '/img/guides/icons/dark/Sentry.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry',
  },
  // Security & Quality
  {
    name: 'Snyk',
    category: 'security',
    icon: '/img/guides/icons/Snyk.svg',
    darkIcon: '/img/guides/icons/dark/Snyk.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk',
  },
  {
    name: 'Wiz',
    category: 'security',
    icon: '/img/guides/icons/Wiz.svg',
    darkIcon: '/img/guides/icons/dark/Wiz.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz',
  },
  {
    name: 'SonarQube',
    category: 'security',
    icon: '/img/guides/icons/SonarQube.svg',
    darkIcon: '/img/guides/icons/dark/SonarQube.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube',
  },
  {
    name: 'Aikido',
    category: 'security',
    icon: '/img/guides/icons/Aikido.svg',
    darkIcon: '/img/guides/icons/dark/Aikido.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/aikido',
  },
  {
    name: 'Checkmarx',
    category: 'security',
    icon: '/img/guides/icons/Checkmarx.svg',
    darkIcon: '/img/guides/icons/dark/Checkmarx.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx',
  },
  {
    name: 'Armorcode',
    category: 'security',
    icon: '/img/guides/icons/Armorcode.svg',
    darkIcon: '/img/guides/icons/dark/Armorcode.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/code-quality-security/armorcode',
  },
  // Feature Management
  {
    name: 'Launchdarkly',
    category: 'feature',
    icon: '/img/guides/icons/Launchdarkly.svg',
    darkIcon: '/img/guides/icons/dark/Launchdarkly.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly',
  },
  // Incident Management
  {
    name: 'PagerDuty',
    category: 'incident',
    icon: '/img/guides/icons/PagerDuty.svg',
    darkIcon: '/img/guides/icons/dark/PagerDuty.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty',
  },
  {
    name: 'StatusPage',
    category: 'incident',
    icon: '/img/guides/icons/StatusPage.svg',
    darkIcon: '/img/guides/icons/dark/StatusPage.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage',
  },
  {
    name: 'FireHydrant',
    category: 'incident',
    icon: '/img/guides/icons/FireHydrant.svg',
    darkIcon: '/img/guides/icons/dark/FireHydrant.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant',
  },
  {
    name: 'OpsGenie',
    category: 'incident',
    icon: '/img/guides/icons/OpsGenie.svg',
    darkIcon: '/img/guides/icons/dark/OpsGenie.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie',
  },
  {
    name: 'ServiceNow',
    category: 'incident',
    icon: '/img/guides/icons/ServiceNow.svg',
    darkIcon: '/img/guides/icons/dark/ServiceNow.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow',
  },
  {
    name: 'Dynatrace',
    category: 'monitoring',
    icon: '/img/guides/icons/Dynatrace.svg',
    darkIcon: '/img/guides/icons/dark/Dynatrace.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace',
  },
  // Cloud Cost
  {
    name: 'Kubecost',
    category: 'cost',
    icon: '/img/guides/icons/Kubecost.svg',
    darkIcon: '/img/guides/icons/dark/Kubecost.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost',
  },
  {
    name: 'Opencost',
    category: 'cost',
    icon: '/img/guides/icons/Opencost.svg',
    darkIcon: '/img/guides/icons/dark/Opencost.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost',
  },
  {
    name: 'Kafka',
    category: 'event',
    icon: '/img/guides/icons/Kafka.svg',
    darkIcon: '/img/guides/icons/dark/Kafka.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka',
  },
  // Identity providers
  {
    name: 'Okta',
    category: 'identity-providers',
    icon: '/img/guides/icons/Okta.svg',
    darkIcon: '/img/guides/icons/dark/Backstage.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/identity-providers/okta',
  },
  {
    name: 'Microsoft Entra ID',
    category: 'identity-providers',
    iconName: 'Azure',
    icon: '/img/guides/icons/Azure.svg',
    darkIcon: '/img/guides/icons/Azure.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/identity-providers/azure-ad',
  },
  {
    name: 'Amplication',
    category: 'other',
    icon: '/img/guides/icons/Amplication.svg',
    darkIcon: '/img/guides/icons/dark/Amplication.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/other/amplication',
  },
  {
    name: 'Backstage',
    category: 'other',
    icon: '/img/guides/icons/Backstage.svg',
    darkIcon: '/img/guides/icons/dark/Backstage.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/other/backstage',
  },
  {
    name: 'Slack',
    category: 'other',
    icon: '/img/guides/icons/Slack.svg',
    darkIcon: '/img/guides/icons/Slack.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/other/slack',
  },
  {
    name: 'Ocean custom',
    category: 'other',
    iconName: 'APIcatalog',
    icon: '/img/guides/icons/APIcatalog.svg',
    darkIcon: '/img/guides/icons/dark/APIcatalog.svg',
    docsUrl: '/build-your-software-catalog/custom-integration/ocean-custom-integration/overview',
  },
  {
    name: 'Github Copilot',
    category: 'ai-agents',
    icon: '/img/guides/icons/GithubCopilot.svg',
    darkIcon: '/img/guides/icons/dark/GithubCopilot.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/ai-agents/github-copilot',
  },
  {
    name: 'Claude AI',
    category: 'ai-agents',
    icon: '/img/guides/icons/ClaudeAI.svg',
    darkIcon: '/img/guides/icons/dark/ClaudeAI.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/ai-agents/claude',
  },
  {
    name: 'Cursor',
    category: 'ai-agents',
    icon: '/img/guides/icons/Cursor.svg',
    darkIcon: '/img/guides/icons/dark/Cursor.svg',
    docsUrl: '/build-your-software-catalog/sync-data-to-catalog/ai-agents/cursor',
  }
];

export const categories = {
  'All': 'all',
  'Git': 'git',
  'Kubernetes stack': 'kubernetes',
  'Cloud providers': 'cloud-providers',
  'IaC': 'iac',
  'Incident management': 'incident',
  'Project management': 'project',
  'Code quality & security': 'security',
  'Feature management': 'feature',
  'APM & alerting': 'monitoring',
  'Cloud cost': 'cost',
  'Event processing': 'event',
  'CI/CD': 'cicd',
  'AI agents': 'ai-agents',
  'Identity providers': 'identity-providers',
  'Other': 'other',
}; 