apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-03-29T22:43:00Z"
  generation: 1
  name: crossplane-contrib-provider-http-22f7bb4b28b5
  namespace: crossplane-system
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: crossplane-contrib-provider-http-22f7bb4b28b5
    uid: ded0c39e-e6bb-49b4-a295-16738db87702
  resourceVersion: "12276294"
  uid: 13e767a8-3aaa-4ac9-8ffa-f9d1a7331aa3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pkg.crossplane.io/provider: provider-http
      pkg.crossplane.io/revision: crossplane-contrib-provider-http-22f7bb4b28b5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        pkg.crossplane.io/provider: provider-http
        pkg.crossplane.io/revision: crossplane-contrib-provider-http-22f7bb4b28b5
    spec:
      containers:
      - env:
        - name: TLS_CLIENT_CERTS_DIR
          value: /tls/client
        - name: TLS_SERVER_CERTS_DIR
          value: /tls/server
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ESS_TLS_CERTS_DIR
          value: $(TLS_CLIENT_CERTS_DIR)
        - name: WEBHOOK_TLS_CERT_DIR
          value: $(TLS_SERVER_CERTS_DIR)
        image: xpkg.upbound.io/crossplane-contrib/provider-http:v0.2.0
        imagePullPolicy: IfNotPresent
        name: package-runtime
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 2000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls/client
          name: tls-client-certs
          readOnly: true
        - mountPath: /tls/server
          name: tls-server-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccount: crossplane-contrib-provider-http-22f7bb4b28b5
      serviceAccountName: crossplane-contrib-provider-http-22f7bb4b28b5
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-client-certs
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          secretName: crossplane-contrib-provider-http-tls-client
      - name: tls-server-certs
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          secretName: crossplane-contrib-provider-http-tls-server
status:
  conditions:
  - lastTransitionTime: "2024-03-29T22:43:00Z"
    lastUpdateTime: "2024-03-29T22:43:05Z"
    message: ReplicaSet "crossplane-contrib-provider-http-22f7bb4b28b5-7b49879d86"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-30T07:29:51Z"
    lastUpdateTime: "2024-04-30T07:29:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
