import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  academySidebar: [
    {
      type: "doc",
      id: "academy/introduction",
    },
    {
      type: "html",
      value: '<hr style="margin: 0.8rem">',
    },
    {
      type: "doc",
      id: "academy/platform-engineer-track",
    },
    {
      type: "doc",
      id: "academy/developer-track",
    },
    // {
    //   type: "doc",
    //   id: "guides/guides",
    // },
    //{type: 'autogenerated', dirName: 'academy'},
  ],
};

export default sidebar.academySidebar;
