name: Bug Report 🪲
description: Create a bug report to help us improve
title: "[Bug/Typo]: "
labels: ["Bug Report", "Needs Triage"]
body:
  - type: textarea
    id: bug
    attributes:
      label: Description
      description: |
        The bug, mistake, typo or other issue you noticed in the docs. Please include a thorough explanation and links to pages in the documentation if relevant
      placeholder: I found a typo in the docs' [Quickstart](https://docs.port.io)
    validations:
      required: true
