name: Feature Proposal 🚀
description: Submit a proposal for a new feature
title: "[Feature]: "
labels: [":rocket: Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: "🚀 Feature Proposal"
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Motivation and example
      description: Outline your motivation for the proposal. How will it make Port's documentation better? Provide a small example of a use-case this addition helps with
    validations:
      required: true
