openapi: 3.0.1
info:
  title: Port API
  version: '1.0'
servers:
  - url: https://api.port.io
  - url: https://api.us.port.io
components:
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
paths:
  '/v1/blueprints/{blueprint_identifier}/permissions':
    get:
      description: This route allows you to retrieve the permissions of a blueprint.<br/><br/>To learn more about permissions, check out the [documentation](https://docs.port.io/build-your-software-catalog/set-catalog-rbac/examples).
      summary: Get a blueprint's permissions
      tags:
        - Blueprints
      security:
        - bearer:
            - 'read:blueprints'
    patch:
      summary: Patch a blueprint's permissions
      description: This route allows you to patch the permissions of a blueprint.<br/><br/>To learn more about permissions, check out the [documentation](https://docs.port.io/build-your-software-catalog/set-catalog-rbac/examples).
      tags:
        - Blueprints
      security:
        - bearer: []
  /v1/auth/access_token:
    post:
      summary: Create an access token
      description: This route allows you to create an access token for your Port account. You can use this token to authenticate your requests to the Port API.<br/><br/>To obtain your client ID and client secret, go to your [Port application](https://app.getport.io), click on the `...` button in the top right corner, then click `Credentials`.
      tags:
        - Authentication / Authorization
  '/v1/blueprints/{blueprint_identifier}/entities':
    post:
      summary: Create an entity
      description: This route allows you to create an entity in your software catalog based on an existing blueprint in your data model. It can also be used to overwrite or update an existing entity.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
    get:
      summary: Get all entities of a blueprint
      description: This route allows you to fetch all entities in your software catalog based on a given blueprint.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer:
            - 'read:entities'
  '/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}':
    patch:
      summary: Patch an entity
      description: This route allows you to edit a specific entity in your software catalog and update its properties.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
    put:
      summary: Change an entity
      description: This route allows you to edit a specific entity in your software catalog and update its properties.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
    get:
      summary: Get an entity
      description: This route allows you to fetch a specific entity in your software catalog.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer:
            - 'read:entities'
    delete:
      summary: Delete an entity
      description: This route allows you to delete a specific entity in your software catalog.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
  '/v1/blueprints/{blueprint_identifier}/entities-count':
    get:
      summary: Get a blueprint's entity count
      description: This route allows you to count the number of entities in a specific blueprint in your software catalog.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
  '/v1/blueprints/{blueprint_identifier}/all-entities':
    delete:
      summary: Delete all entities of a blueprint
      description: This route allows you to delete all entities of a specific blueprint in your software catalog.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).
      tags:
        - Entities
      security:
        - bearer: []
  /v1/entities/search:
    post:
      summary: Search entities
      tags:
        - Entities
      description: This route allows you to search for entities in your software catalog based on a given set of rules.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).<br/><br/>For more details about Port's search mechanism, rules, and operators - see the [search & query documentation](https://docs.port.io/search-and-query/).
      security:
        - bearer:
            - 'read:entities'
  /v1/entities/aggregate:
    post:
      summary: Aggregate entities
      tags:
        - Entities
      description: This route allows you to perform an aggregation function on a blueprint's entities based on a given set of rules.<br/><br/>To learn more about entities, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#entities).<br/><br/>For more details about Port's search mechanism, rules, and operators - see the [search & query documentation](https://docs.port.io/search-and-query/).
      security:
        - bearer:
            - read:entities
  /v1/entities/aggregate-over-time:
    post:
      summary: Aggregate entities over time
      tags:
        - Entities
      description: This route allows you to perform an aggregation function on a blueprint's entities over a given time range.<br/><br/>To learn more about entities, check out the [entity documentation](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/#entities).<br/><br/>For more details about Port's search mechanism, rules, and operators - see the [search & query documentation](https://docs.getport.io/search-and-query/).
      security:
        - bearer:
            - read:entities
  /v1/blueprints/{blueprint_identifier}/entities/search:
    post:
      summary: Search a blueprint's entities
      description: This route allows you to search your software catalog for a specific blueprint's entities, based on a given set of rules.<br/>The returned entities are paginated for improved performance.<br/><br/>To learn more about entities, check out the [entity documentation](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/#entities).<br/><br/>For more details about Port's search mechanism, rules, and operators - see the [search & query documentation](https://docs.[...]
      tags:
        - Entities
      security:
        - bearer:
            - read:entities
  /v1/blueprints:
    get:
      summary: Get all blueprints
      description: This route allows you to fetch all blueprints in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer:
            - 'read:blueprints'
    post:
      summary: Create a blueprint
      description: This route allows you to create a new blueprint in your data model.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer:
            - 'create:blueprints'
  '/v1/blueprints/{identifier}':
    get:
      summary: Get a blueprint
      description: This route allows you to fetch a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer:
            - 'read:blueprints'
    put:
      summary: Change a blueprint
      description: This route allows you to change a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
    patch:
      summary: Patch a blueprint
      description: This route allows you to patch a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
    delete:
      summary: Delete a blueprint
      description: This route allows you to delete a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
  '/v1/blueprints/{identifier}/properties/{property_name}/rename':
    patch:
      summary: Rename a property in a blueprint
      description: This route allows you to change the identifier of a property in a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
  '/v1/blueprints/{identifier}/mirror/{mirror_name}/rename':
    patch:
      summary: Rename a blueprint's mirror property
      description: This route allows you to change the identifier of a mirror property in a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
  '/v1/blueprints/{identifier}/relations/{relation_identifier}/rename':
    patch:
      summary: Rename a blueprint's relation
      description: This route allows you to change the identifier of a relation in a specific blueprint in your Port account.<br/><br/>To learn more about blueprints, check out the [documentation](https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/).
      tags:
        - Blueprints
      security:
        - bearer: []
  /v1/actions:
    post:
      summary: Create an action/automation
      description: This route allows you to create a new self-service action or automation in your Port account.<br/><br/>To learn more about actions and automations, check out the [documentation](https://docs.port.io/actions-and-automations/).
      tags:
        - Actions
      security:
        - bearer:
            - create:actions
    get:
      summary: Get actions/automations
      description: This route allows you to fetch one or more self-service actions and/or automations in your Port account.<br/><br/>The call will perform a logical `AND` between all query parameters below, and return all actions and automations that match the criteria.<br/><br/>To learn more about actions and automations, check out the [documentation](https://docs.port.io/actions-and-automations/).<br/>
      tags:
        - Actions
      security:
        - bearer:
            - read:actions
  "/v1/actions/{action_identifier}":
    put:
      summary: Update an action/automation
      description: This route allows you to update an existing self-service action or automation in your Port account.<br/><br/>To learn more about actions and automations, check out the [documentation](https://docs.port.io/actions-and-automations/).<br/>
      tags:
        - Actions
      security:
        - bearer:
            - update:actions
    get:
      summary: Get an action/automation
      description: This route allows you to fetch the details of a self-service action or automation.<br/><br/>To learn more about actions and automations, check out the [documentation](https://docs.port.io/actions-and-automations/).<br/>
      tags:
        - Actions
      security:
        - bearer:
            - read:actions
    delete:
      summary: Delete an action/automation
      description: This route allows you to delete a self-service action or automation.<br/><br/>To learn more about actions and automations, check out the [documentation](https://docs.port.io/actions-and-automations/).<br/>
      tags:
        - Actions
      security:
        - bearer:
            - delete:actions
  "/v1/actions/{action_identifier}/permissions":
    get:
      summary: Get an action's permissions
      description: This route allows you to fetch the permissions of a self-service action.<br/><br/>To learn more about action RBAC, check out the [documentation](https://docs.port.io/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/).
      tags:
        - Actions
      security:
        - bearer: []
    patch:
      summary: Update an action's permissions
      description: This route allows you to update the permissions of a self-service action.<br/><br/>To learn more about action RBAC, check out the [documentation](https://docs.port.io/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/).
      tags:
        - Actions
      security:
        - bearer: []
  "/v1/actions/{action_identifier}/runs":
    post:
      summary: Execute a self-service action
      description: This route allows you to execute a self-service action, thus creating an action run.<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).
      tags:
        - Action Runs
      security:
        - bearer: []
  '/v1/actions/runs/{run_id}':
    patch:
      summary: Patch an action run
      description: This route allows you to patch an action run's details. This can be used to update the run's status & label, and add links to it (e.g. external logs of the job runner).<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).
      tags:
        - Action Runs
      security:
        - bearer: []
    get:
      summary: Get an action run's details
      description: This route allows you to fetch the details of an action run.<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).
      tags:
        - Action Runs
      security:
        - bearer:
            - 'read:runs'
  '/v1/actions/runs/{run_id}/approval':
    patch:
      summary: Approve an action run
      description: This route allows you to approve or decline a request to execute an action that requires approval.<br/><br/>To learn more about manual approval for actions, check out the [documentation](https://docs.port.io/create-self-service-experiences/set-self-service-actions-rbac/#configure-manual-approval-for-actions).
      tags:
        - Action Runs
      security:
        - bearer: []
  "/v1/actions/runs/{run_id}/approvers":
    get:
      summary: Get an action run's approvers
      description: This route allows you to fetch the approvers of a specific action run.<br/><br/>To learn more about manual approval for actions, check out the [documentation](https://docs.port.io/create-self-service-experiences/set-self-service-actions-rbac/#configure-manual-approval-for-actions).
      tags:
        - Action Runs
      security:
        - bearer:
            - read:runs
  /v1/actions/runs:
    get:
      summary: Get all action runs
      description: This route allows you to fetch all action runs in your Port account. The route will perform a logical `AND` between all query parameters below, and return all action runs that match the criteria.<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).
      tags:
        - Action Runs
      security:
        - bearer:
            - 'read:runs'
  '/v1/actions/runs/{run_id}/logs':
    post:
      summary: Add a log to an action run
      description: This route allows you to send a log message back to Port, which will be displayed in the action run's page. You can also use this route to update the run's termination status (SUCCESS/FAILURE) and label describing the status.<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).  
      tags:
        - Action Runs
      security:
        - bearer: []
    get:
      summary: Get an action's run logs
      description: This route allows you to fetch the logs from an action run.<br/><br/>To learn more about action runs, check out the [documentation](https://docs.port.io/create-self-service-experiences/reflect-action-progress/).
      tags:
        - Action Runs
      security:
        - bearer: []
  /v1/teams:
    get:
      summary: Get all teams in your organization
      description: This route allows you to fetch all of the teams in your Port organization.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'read:teams'
    post:
      summary: Create a team
      description: This route allows you to create a new team in your Port organization.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'create:teams'
  '/v1/teams/{name}':
    get:
      summary: Get a team
      description: This route allows you to fetch a specific team in your Port organization.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'read:teams'
    patch:
      summary: Patch a team
      description: This route allows you to patch a team's details. This can be used to update the team's name, users, and description.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'update:teams'
    put:
      summary: Change a team
      description: This route allows you to change a team's details. This can be used to update the team's name, users, and description.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'update:teams'
    delete:
      summary: Delete a team
      description: This route allows you to delete a team in your Port organization.<br/><br/>To learn more about teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Teams
      security:
        - bearer:
            - 'delete:teams'
  /v1/users:
    get:
      summary: Get all users in your organization
      description: This route allows you to fetch all of the users in your Port organization.<br/><br/>To learn more about users, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Users
      security:
        - bearer:
            - 'read:users'
  /v1/users/invite:
    post:
      summary: Invite a user to your organization
      description: This route allows you to invite a user to your Port organization.<br/><br/>To learn more about users, roles, and teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Users
      security:
        - bearer:
            - 'create:users'
  '/v1/users/{user_email}':
    get:
      summary: Get a user
      description: This route allows you to fetch a specific user in your Port organization.<br/><br/>To learn more about users, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Users
      security:
        - bearer:
            - 'read:users'
    patch:
      summary: Patch a user
      description: This route allows you to patch a user's details. This can be used to update the user's role/s and team/s.<br/><br/>To learn more about users, roles, and teams, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Users
      security:
        - bearer:
            - 'update:users'
    delete:
      summary: Delete a user
      description: This route allows you to delete a user in your Port organization.<br/><br/>To learn more about users, check out the [documentation](https://docs.port.io/sso-rbac/rbac-overview/).
      tags:
        - Users
      security:
        - bearer:
            - 'delete:users'
  /v1/audit-log:
    get:
      summary: Get audit logs
      description: This route allows you to fetch audit logs from your Port account. Your audit logs can also be viewed via [Port's UI](https://app.getport.io/settings/AuditLog).<br/><br/>This route will perform a logical `AND` between all query parameters below, and return all logs that match the criteria.
      tags:
        - Audit
      security:
        - bearer:
            - 'read:audit-log'
  '/v1/blueprints/{blueprint_identifier}/scorecards':
    post:
      summary: Create a scorecard
      description: This route allows you to create a scorecard for a given blueprint. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer: []
    put:
      summary: Change scorecards
      description: This route allows you to modify one or more scorecards of a given blueprint. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer: []
    get:
      summary: Get a blueprint's scorecards
      description: This route allows you to fetch all scorecards for a given blueprint. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer:
            - 'read:scorecards'
  '/v1/blueprints/{blueprint_identifier}/scorecards/{scorecard_identifier}':
    put:
      summary: Change a scorecard
      description: This route allows you to modify a specific scorecard. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer: []
    get:
      summary: Get a scorecard
      description: This route allows you to fetch a specific scorecard. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer:
            - 'read:scorecards'
    delete:
      summary: Delete a scorecard
      description: This route allows you to delete a specific scorecard. A scorecard is a set of rules that define the quality of a blueprint.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer: []
  /v1/scorecards:
    get:
      summary: Get all scorecards
      description: This route allows you to fetch all scorecards in your Port organization.<br/><br/>To learn more about scorecards, check out the [documentation](https://docs.port.io/promote-scorecards/).
      tags:
        - Scorecards
      security:
        - bearer:
            - 'read:scorecards'
  /v1/organization:
    get:
      summary: Get organization details
      description: This route allows you to fetch the details of your Port organization, such as its name, id, and hidden blueprints.
      tags:
        - Organization
      security:
        - bearer: []
    put:
      summary: Update organization details
      description: This route allows you to update the details of your Port organization, such as its name and hidden blueprints.
      tags:
        - Organization
      security:
        - bearer:
            - update:organization
    patch:
      summary: Patch organization details
      description: This route allows you to patch the details of your Port organization, such as its name and hidden blueprints.
      tags:
        - Organization
      security:
        - bearer:
            - update:organization
  '/v1/integration/{identifier}/logs':
    get:
      summary: Get an integration's audit logs
      description: This route allows you to fetch the audit logs of a specific integration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'read:integrations'
  '/v1/integration/{identifier}/config':
    patch:
      summary: Patch an integration's config
      description: This route allows you to modify an integration's configuration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'update:integrations'
  /v1/integration:
    get:
      summary: Get all integrations
      description: This route allows you to fetch all integrations in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'read:integrations'
    post:
      summary: Create an integration
      description: This route allows you to create an integration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'create:integrations'
  '/v1/integration/{identifier}':
    get:
      summary: Get an integration
      description: This route allows you to fetch a specific integration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'read:integrations'
    patch:
      summary: Patch an integration
      description: |
        This route allows you to modify an integration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).<br/>
        :::tip Simple resync
        To trigger a resync of an integration without changing its mapping, simply provide its identifier and leave the body empty.
        :::
      tags:
        - Integrations
      security:
        - bearer:
            - 'update:integrations'
    delete:
      summary: Delete an integration
      description: This route allows you to delete an integration in your Port organization.<br/><br/>To learn more about integrations, check out the [documentation](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/).
      tags:
        - Integrations
      security:
        - bearer:
            - 'delete:integrations'
  /v1/webhooks:
    post:
      summary: Create a webhook
      description: This route allows you to create a webhook in your Port organization. Webhooks provide a way to ingest data from an external tool/platform into Port. You can also create a webhook via the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'create:integrations'
    get:
      summary: Get all webhooks
      description: This route allows you to fetch all webhooks configured in your Port organization. You can also see them in the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'read:integrations'
  '/v1/webhooks/{identifier}':
    patch:
      summary: Patch a webhook
      description: This route allows you to modify a webhook in your Port organization. You can also modify it via the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'update:integrations'
    put:
      summary: Change a webhook
      description: This route allows you to modify a webhook in your Port organization. You can also modify it via the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'update:integrations'
    get:
      summary: Get a webhook
      description: This route allows you to fetch a specific webhook in your Port organization. You can also see it in the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'read:integrations'
    delete:
      summary: Delete a webhook
      description: This route allows you to delete a webhook in your Port organization. You can also delete it via the [data sources page](https://app.getport.io/settings/data-sources) of your Port account.<br/><br/>To learn more about webhooks, check out the [documentation](https://docs.port.io/build-your-software-catalog/custom-integration/webhook/).
      tags:
        - Webhook
      security:
        - bearer:
            - 'delete:integrations'
  /v1/migrations:
    get:
      summary: Get all migrations
      description: This route allows you to fetch all migrations (both past and present) in your Port organization.<br/><br/>The call will perform a logical `AND` operation on the query parameters below, and return all migrations that match the criteria.
      tags:
        - Migrations
      security:
        - bearer:
            - 'read:blueprints'
    post:
      summary: Create a migration
      description: This route allows you to create a migration in your Port organization.<br/><br/>You can use this to migrate data from one blueprint to another, or to convert the data type of a property in a blueprint.
      tags:
        - Migrations
      security:
        - bearer: []
  "/v1/migrations/{migration_id}":
    get:
      summary: Get a migration
      description: This route allows you to fetch a specific migration in your Port organization.
      tags:
        - Migrations
      security:
        - bearer:
            - read:blueprints
  "/v1/migrations/{migration_id}/cancel":
    post:
      summary: Cancel a migration
      description: This route allows you to cancel a running migration in your Port organization.
      tags:
        - Migrations
      security:
        - bearer: []
  /v1/organization/secrets:
    get:
      description: This route allows you to retrieve all of the secrets in your organization.<br/><br/>To learn more about secrets management in Port, check out the [documentation](https://docs.port.io/sso-rbac/port-secrets).
      summary: Get all organization secrets
      tags:
        - Organization
      security:
        - bearer:
            - read:secrets
    post:
      summary: Create an organization secret
      description: This route allows you to create an organization secret.<br/><br/>To learn more about secrets management in Port, check out the [documentation](https://docs.port.io/sso-rbac/port-secrets).
      tags:
        - Organization
      security:
        - bearer:
            - create:secrets
  "/v1/organization/secrets/{secret_name}":
    get:
      summary: Get an organization secret
      description: This route allows you to retrieve a specific secret in your organization.<br/><br/>To learn more about secrets management in Port, check out the [documentation](https://docs.port.io/sso-rbac/port-secrets).
      tags:
        - Organization
      security:
        - bearer:
            - read:secrets
    patch:
      summary: Patch an organization secret
      description: This route allows you to patch an organization secret.<br/><br/>To learn more about secrets management, check out the [documentation](https://docs.port.io/sso-rbac/port-secrets).
      tags:
        - Organization
      security:
        - bearer:
            - update:secrets
    delete:
      summary: Delete an organization secret
      description: This route allows you to delete an organization secret.<br/><br/>To learn more about secrets management in Port, check out the [documentation](https://docs.port.io/sso-rbac/port-secrets).
      tags:
        - Organization
      security:
        - bearer:
            - delete:secrets
  /v1/apps:
    get:
      summary: Get all credentials
      description: This route allows you to fetch all credentials in your Port organization.<br/>
      tags:
        - Apps
      security:
        - bearer:
            - read:apps
    post:
      summary: Create credentials
      description: This route allows you to create a set of credentials in your Port organization, containing a `client ID` and `client secret`.<br/>
      tags:
        - Apps
      security:
        - bearer:
            - update:apps
  "/v1/apps/{id}/rotate-secret":
    post:
      summary: Rotate secret
      description: This route allows you to rotate the secret of a set of credentials in your Port organization.<br/>
      tags:
        - Apps
      security:
        - bearer:
            - update:apps
  "/v1/apps/{id}":
    delete:
      summary: Delete credentials
      description: This route allows you to delete a set of credentials in your Port organization.<br/>
      tags:
        - Apps
      security:
        - bearer:
            - update:apps
    put:
      summary: Update credentials
      description: This route allows you to update the name of a set of credentials in your Port organization.<br/>
      tags:
        - Apps
      security:
        - bearer:
            - update:apps