import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  guidessidebar: [
    {
      type: "doc",
      id: "guides/onboarding-guides",
    },
    {
      type: "html",
      value: '<hr style="margin: 0.8rem">',
    },
    {type: 'autogenerated', dirName: 'guides/prod'},
    {
      type: "html",
      value: '<hr style="margin: 0.8rem">',
    },
    {
      type: "doc",
      id: "guides/all-guides",
    },
  ],
};

export default sidebar.guidessidebar;
