import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  guidessidebar: [
    // {
    //   type: "doc",
    //   id: "guides/guides",
    // },
    {type: 'autogenerated', dirName: 'guides'},
    {
      type: "html",
      value: '<hr style="margin: 0.8rem">',
    },
  ],
};

export default sidebar.guidessidebar;
