import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  solutionssidebar: [
    {type: 'autogenerated', dirName: 'solutions'},
  ],
};

export default sidebar.solutionssidebar; 