const guideMetadata = require('./guide-metadata.json');

export const tagsCategoryMap = {

    "Solutions": ["Security", "Engineering Intelligence", "Autonomous Ticket Resolution", "Self Healing Incidents", "Agentic Work Management"],
    "Use-cases": ["K8s for devs", "IaC for devs", "Cloud access management", "Feature flag management", /*"Cloud cost",*/ "Dev environments", "Dependency management", "API catalog", "Approval workflow"],
    "Port pillars": ["Actions", "AI", "Automations", "Dashboards", "Scorecards", "Access controls"],

    Technologies: [
        "GitHub",
        "Github Copilot",
        "GitLab",
        "BitBucket",
        "AzureDevops",
        "Claude Code",
        "n8n",
        "Azure",
        "Webhook",
        "Kafka",
        "Jenkins",
        "Jira",
        "Kubernetes",
        "ArgoCD",
        "AWS",
        "Slack",
        "PagerDuty",
        "Terraform",
        // "GCP",
        // "Kubecost",
        "Launchdarkly",
        // "Linear",
        // "Opencost",
        "Snyk",
        "Wiz",
        "Datadog",
        "Dynatrace",
        "New Relic",
        "ServiceNow",
        "SonarQube",
        "Humanitec",
        "IncidentIO",
    ]
};

export const availableGuides = [
    {
        title: "Scaffold a new service",
        description: "Create a self-service action that scaffolds a new service",
        tags: ["Actions"],
        additionalTags: ["BitBucket", "GitHub", "GitLab"],
        logos: ["Git"],
        // category: "Getting started",
        link: "/guides/all/scaffold-a-new-service",
    },
    {
        title: "Ensure production readiness",
        description: "Define and track metrics for your services to ensure their production readiness",
        tags: ["Autonomous Ticket Resolution", "Scorecards", "PagerDuty"],
        additionalTags: ["BitBucket", "GitHub", "GitLab"],
        logos: ["PagerDuty", "Git"],
        // category: "Getting started",
        link: "/guides/all/ensure-production-readiness",
    },
    {
        title: "Create cloud resources using IaC",
        description: "Create a self-service action that provisions cloud resources from a pre-defined template in your Git repository",
        tags: ["IaC for devs", "AWS", "Actions", "Cloud access management"],
        additionalTags: ["BitBucket", "GitHub", "GitLab"],
        logos: ["AWS", "Git"],
        // category: "Getting started",
        link: "/guides/all/create-cloud-resource-using-iac",
    },
    {
        title: "Visualize your services' k8s runtime",
        description: "Create views to track the health, status, and other standards of your services' k8s runtime",
        tags: ["K8s for devs", "Actions", "Dashboards", "Scorecards"],
        logos: ["Kubernetes" ],
        // category: "Getting started",
        link: "/guides/all/visualize-service-k8s-runtime",
    },
    {
        title: "Visualize your services' k8s runtime using ArgoCD",
        description: "Create views to track the health, status, and other standards of your services' k8s runtime using ArgoCD",
        tags: ["K8s for devs", "ArgoCD", "Actions", "Dashboards", "Scorecards"],
        logos: ["ArgoCD", "Kubernetes"],
        // category: "Getting started",
        link: "/guides/all/visualize-service-argocd-runtime",
    },
    {
        title: "Enrich services using Gitops",
        description: "Empower developers to independently enrich their services using a self-service action",
        tags: ["Actions"],
        additionalTags: ["BitBucket", "GitHub", "GitLab"],
        logos: ["Git"],
        // category: "Getting started",
        link: "/guides/all/let-developers-enrich-services-using-gitops",
    },
    {
        title: "Slack reminders for scorecards",
        description: "Send a Slack reminder for uncompleted scorecard rules using a self-service action",
        tags: ["Engineering Intelligence", "Actions", "Scorecards"],
        logos: ["Slack"],
        // category: "Getting started",
        link: "/guides/all/setup-slack-reminders",
    },
    {
        title: "Create & use surveys in your portal",
        description: "Create & use surveys in your portal to collect feedback from your users",
        tags: ["Engineering Intelligence", "Actions"],
        logos: ["Actions"],
        // category: "Experiences",
        link: "/guides/all/create-and-use-surveys-in-your-portal",
    },
    {
        title: "Create & track DORA metrics in your portal",
        description: "Create & track DORA metrics in your portal to measure engineering performance",
        tags: ["Engineering Intelligence", "Actions"],
        logos: ["Actions"],
        // category: "Experiences",
        link: "/guides/all/create-and-track-dora-metrics-in-your-portal",
    },
    {
        title: "Set up deployments using GitLab merge requests or jobs",
        description: "Set up deployments using GitLab merge requests or jobs",
        tags: ["Engineering Intelligence"],
        logos: ["GitLab"],
        // category: "Experiences",
        link: "/guides/all/set-up-deployments-dora-gitlab",
    },
    {
        title: "Set up DORA metrics using Jira",
        description: "Configure DORA metrics tracking using Jira for both deployments and incidents",
        tags: ["Engineering Intelligence", "Jira"],
        logos: ["Jira"],
        // category: "Experiences",
        link: "/guides/all/setup-dora-metrics-jira",
    },
    {
        title: "IAM permission management",
        description: "Empower developers to independently enrich their services using a self-service action",
        tags: ["Cloud access management", "Actions", "Access controls"],
        logos: ["AWS" ],
        // category: "Getting started",
        link: "/guides/all/iam-permissions-guide",
    },
    {
        title: "Automate Slack alerts for Overdue PRs",
        description: "Send a Slack notification for pull requests that have been open longer than a specified time using an automation",
        tags: ["Autonomous Ticket Resolution", "Automations"],
        logos: ["Slack"],
        // category: "Getting started",
        link: "/guides/all/automate-slack-alert-for-overdue-prs",
    },
    {
        title: "Manage resources using Kubernetes CRDs",
        description: "Integrate Kubernetes CRDs with Port and expose them in the Port UI for developers to use",
        tags: ["K8s for devs", "Actions"],
        logos: ["Kubernetes"],
        // category: "Getting started",
        link: "/guides/all/manage-resources-using-k8s-crds",
    },
    {
        title: "Auto-create Slack channel & GitHub issue for PagerDuty incidents",
        description: "Automatically create a Slack channel and GitHub issue when a PagerDuty incident is reported",
        tags: ["Self Healing Incidents", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-slack-channel-for-reported-incident",
    },
    {
        title: "Resolve PagerDuty incidents",
        description: "Create a self-service action to resolve incidents and notify stakeholders",
        tags: ["Self Healing Incidents", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/resolve-pagerduty-incident",
    },
    {
        title: "Connect GitHub pull request with Jira Issue",
        description: "Create a logical connection between your GitHub PRs and their corresponding Jira issues",
        tags: ["Autonomous Ticket Resolution", "Jira", "GitHub"],
        logos: ["Jira", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/connect-github-pr-with-jira-issue",
    },
    /*
    {
        title: "Connect GitHub repository (service) to a Launchdarkly project",
        description: "Create a logical connection between your services and their corresponding Launchdarkly projects",
        tags: ["Feature flag management", "Launchdarkly", "GitHub"],
        logos: ["Launchdarkly", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/connect-github-repository-with-launchdarkly-project",
    },
    */
    /*
    {
        title: "Connect Launchdarkly feature flag to a service",
        description: "Create a logical connection between a feature flag and a service",
        tags: ["Feature flag management", "Launchdarkly"],
        logos: ["Launchdarkly", "Git"],
        // category: "Getting started",
        link: "/guides/all/connect-launchdarkly-flag-to-service",
    },
    */
    {
        title: "Ingest cloud resources using Dynatrace",
        description: "Ingest any cloud resources from your Dynatrace environment into Port",
        tags: ["Dynatrace"],
        logos: ["Dynatrace"],
        // category: "Getting started",
        link: "/guides/all/ingest-cloud-resources-using-dynatrace",
    },
    {
        title: "Connect GitHub pull request to SonarQube analysis",
        description: "Create a logical connection between your GitHub PRs and their corresponding SonarQube analyses",
        tags: ["Security", "SonarQube", "GitHub"],
        logos: ["SonarQube", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/connect-github-pr-with-sonar-analysis",
    },
    {
        title: "Humanitec Integration",
        description: "Ingest various Humanitec resources into your Port software catalog",
        tags: ["Humanitec"],
        logos: ["Humanitec"],
        // category: "Getting started",
        link: "/guides/all/humanitec-integration",
    },
    {
        title: "Pull-request metrics",
        description: "Compute pull-request metrics for a GitHub repository",
        tags: ["Engineering Intelligence", "GitHub"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/pull-request-metrics",
    },
    {
        title: "Connect CODEOWNERS with Service, Team & User",
        description: "Create a logical connection between your GitHub CODEOWNERS and their corresponding services, teams, and users",
        tags: ["Access controls", "GitHub"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/connect-github-codeowners-with-service-team-and-user",
    },
    {
        title: "Manage an S3 Bucket Lifecycle",
        description: "Create and manage an S3 bucket using Port & Terraform",
        tags: ["IaC for devs", "AWS", "Terraform"],
        logos: ["AWS", "Terraform"],
        // category: "Getting started",
        link: "/guides/all/s3-bucket",
    },
    {
        title: "Manage a Developer Environment Lifecycle",
        description: "Create and manage a developer environment in AWS using Port & Terraform",
        tags: ["Dev environments", "IaC for devs", "AWS", "Terraform"],
        logos: ["AWS", "Terraform"],
        // category: "Getting started",
        link: "/guides/all/create-dev-env",
    },
    {
        title: "Manage integration mapping using Terraform",
        description: "Configure integration mapping using Port & Terraform",
        tags: ["IaC for devs", "Terraform"],
        logos: ["Terraform"],
        // category: "Getting started",
        link: "/guides/all/import-and-manage-integration",
    },
    {
        title: "Set up a basic execution runner using Kafka & AWS Lambda",
        description: "Deploy an AWS Lambda function that will perform an action based on Port action invocations",
        tags: ["Kafka", "Actions", "AWS"],
        logos: ["Kafka", "AWS"],
        // category: "Getting started",
        link: "/guides/all/execution-basic-runner-using-aws-lambda",
    },
    {
        title: "Create an S3 bucket using Self-Service Actions",
        description: "Create an S3 bucket using a webhook backend",
        tags: ["Webhook", "AWS", "Actions"],
        logos: ["AWS", "Webhook"],
        // category: "Getting started",
        link: "/guides/all/s3-using-webhook",
    },
    {
        title: "Create a GitHub Secret",
        description: "Create a GitHub secret using a GitHub workflow backend",
        tags: ["GitHub", "Actions"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-github-secret",
    },
    {
        title: "Delete a GitHub Repository",
        description: "Create a self-service action that uses a GitHub workflow backend to delete a GitHub repository",
        tags: ["GitHub", "Actions"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/delete-repository",
    },
    {
        title: "Manage GitHub Pull Requests",
        description: "Create a self-service action that uses a GitHub workflow backend to close/approve/merge pull requests",
        tags: ["Autonomous Ticket Resolution", "GitHub", "Actions"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/manage-pull-requests",
    },
    {
        title: "Nudge Pull Request Reviewers",
        description: "Create a self-service action that nudges reviewers of a pull request",
        tags: ["Autonomous Ticket Resolution", "GitHub", "Actions", "Slack"],
        logos: ["GitHub", "Slack"],
        // category: "Getting started",
        link: "/guides/all/nudge-pr-reviewers",
    },
    {
        title: "Promote Deployment to Production",
        description: "Create a self-service action that promotes an image from staging to production",
        tags: ["Autonomous Ticket Resolution", "Actions", "GitHub"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/promote-to-production",
    },
    {
        title: "Broadcast message to API consumers",
        description: "Create a self-service action that sends a Slack message to designated channels",
        tags: ["GitHub", "Actions", "Slack"],
        logos: ["GitHub", "Slack"],
        // category: "Getting started",
        link: "/guides/all/broadcast-api-consumers-message",
    },
    {
        title: "Lock and Unlock Services",
        description: "Create a self-service action that locks and unlocks a service",
        tags: ["Actions", "GitHub"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/lock-and-unlock-services-in-port",
    },
    {
        title: "Create Slack channel for Incident Management",
        description: "Create a self-service action that creates a dedicated Slack channel for a service",
        tags: ["Self Healing Incidents", "Actions", "Slack"],
        logos: ["GitHub", "Slack"],
        // category: "Getting started",
        link: "/guides/all/open-slack-channel",
    },
    {
        title: "Deploy/rollback using ArgoCD",
        description: "Create a self-service action that performs a deployment/rollback using ArgoCD",
        tags: ["K8s for devs", "ArgoCD", "Actions", "GitHub"],
        logos: ["ArgoCD", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/rollback-argocd-deployment",
    },
    {
        title: "Synchronize ArgoCD Application",
        description: "Create a self-service action that synchronizes an ArgoCD application",
        tags: ["K8s for devs", "ArgoCD", "Actions", "GitHub"],
        logos: ["ArgoCD", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/sync-argocd-app",
    },
    {
        title: "Restart ArgoCD Application",
        description: "Create a self-service action that restarts an ArgoCD application",
        tags: ["K8s for devs", "ArgoCD", "Actions", "GitHub"],
        logos: ["ArgoCD", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/restart-argocd-app",
    },
    {
        title: "Change Deployment Replica Count",
        description: "Create a self-service action that changes the replica count of a Kubernetes deployment",
        tags: ["K8s for devs", "Actions", "GitHub"],
        logos: ["Kubernetes", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/change-replica-count",
    },
    {
        title: "Create and manage Kubernetes clusters",
        description: "Create Kubernetes clusters using Crossplane & ArgoCD",
        tags: ["K8s for devs", "ArgoCD", "GitHub"],
        logos: ["ArgoCD", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/manage-clusters",
    },
    {
        title: "Deploy AWS resources using CloudFormation",
        description: "Create a self-service action that deploys AWS resources using an AWS CloudFormation template",
        tags: ["IaC for devs", "AWS", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/deploy-cloudformation-template",
    },
    {
        title: "Create An AWS EC2 Instance",
        description: "Create a self-service action that creates an AWS EC2 instance using a Terraform template",
        tags: ["IaC for devs", "AWS", "Terraform", "Actions", "GitHub"],
        logos: ["AWS", "Terraform", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-an-ec2-instance",
    },
    {
        title: "Deploy S3 Bucket using Crossplane",
        description: "Create a self-service action that deploys Crossplane resources in your Kubernetes cluster",
        tags: ["K8s for devs", "AWS", "Actions"],
        logos: ["Kubernetes", "AWS"],
        // category: "Getting started",
        link: "/guides/all/deploy-s3-bucket-crossplane",
    },
    {
        title: "Manage An AWS EC2 Instance",
        description: "Create a self-service action that terminates/reboots/resizes an AWS EC2 instance",
        tags: ["AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/manage-ec2-instances",
    },
    {
        title: "Provision Cloud Resource using Terraform",
        description: "Create a self-service action that provisions cloud resources using Terraform",
        tags: ["IaC for devs", "Approval workflow", "AWS", "Terraform", "Actions"],
        logos: ["AWS", "Terraform"],
        // category: "Getting started",
        link: "/guides/all/terraform-plan-and-apply-aws-resource",
    },
    {
        title: "Add tags to ECR repository",
        description: "Create a self-service action that adds meaningful tags to an AWS ECR repository",
        tags: ["AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/add-tags-to-ecr-repository",
    },
    {
        title: "Add tags to S3 Bucket",
        description: "Create a self-service action that adds meaningful tags to an AWS S3 bucket",
        tags: ["AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/add-tags-to-s3-bucket",
    },
    {
        title: "Create an EKS cluster and deploy a Node.js app",
        description: "Create a self-service action that provisions an EKS cluster and deploys a Node.js app",
        tags: ["K8s for devs", "AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-eks-cluster-and-deploy-app",
    },
    {
        title: "Build an ECR image",
        description: "Create a self-service action that builds and pushes a Docker image to AWS ECR",
        tags: ["AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/push-image-to-ecr",
    },
    {
        title: "Deploy Azure Resource using Terraform",
        description: "Create a self-service action that deploys a storage account in Azure using Terraform",
        tags: ["IaC for devs", "Azure", "Terraform", "Actions"],
        logos: ["Azure", "Terraform"],
        // category: "Getting started",
        link: "/guides/all/create-azure-resource",
    },
    {
        title: "Add Tags to Azure Resource",
        description: "Create a self-service action that adds tags to an Azure storage account",
        tags: ["Azure", "GitHub", "Actions"],
        logos: ["Azure", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/tag-azure-resource",
    },
    {
        title: "Trigger Datadog Incident",
        description: "Create a self-service action that triggers a Datadog incident",
        tags: ["Self Healing Incidents", "Datadog", "Actions", "Webhook"],
        logos: ["Datadog", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/trigger-datadog-incident",
    },
    {
        title: "Change status and assignee of Jira ticket",
        description: "Create a self-service action that changes the status and assignee of a Jira ticket",
        tags: ["Jira", "GitHub", "Actions", "Webhook", "Automations"],
        logos: ["Jira", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/change-status-and-assignee-of-jira-ticket",
    },
    {
        title: "Create Jira Issue from Dependabot Alert",
        description: "Create a self-service action that creates a Jira issue from a Dependabot alert",
        tags: ["Security", "Jira", "GitHub", "Actions", "Webhook"],
        logos: ["Jira", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-jira-issue-from-dependabot",
    },
    {
        title: "Create Jira issue with automatic label",
        description: "Create a self-service action that creates a Jira issue with a label that links it to a service",
        tags: ["Jira", "GitHub", "Actions", "Webhook", "Automations"],
        logos: ["Jira", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/open-jira-issue-with-automatic-label",
    },
    {
        title: "Report a bug to Jira",
        description: "Create a self-service action that reports a bug to Jira",
        tags: ["Jira", "GitHub", "Actions", "Webhook"],
        logos: ["Jira", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/report-a-bug",
    },
    // {
    //     title: "Toggle LaunchDarkly Feature Flag",
    //     description: "Create a self-service action that toggles a LaunchDarkly feature flag",
    //     tags: ["Feature flag management", "Launchdarkly", "GitHub", "Actions", "Webhook", "Automations"],
    //     logos: ["Launchdarkly", "GitHub"],
    //     // category: "Getting started",
    //     link: "/guides/all/toggle-launchdarkly-feature-flag",
    // },
    {
        title: "Create an Opsgenie Incident",
        description: "Create a self-service action that creates an Opsgenie incident",
        tags: ["Self Healing Incidents", "GitHub", "Actions"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-an-opsgenie-incident",
    },
    {
        title: "Acknowledge Incident In PagerDuty",
        description: "Create a self-service action that acknowledges an incident in PagerDuty",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions","Webhook", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/acknowledge-incident",
    },
    {
        title: "Change the on-call In PagerDuty",
        description: "Create a self-service action that changes the on-call in PagerDuty",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/change-on-call-user",
    },
    {
        title: "Change Incident Owner In PagerDuty",
        description: "Create a self-service action that changes the incident owner in PagerDuty",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/change-pagerduty-incident-owner",
    },
    {
        title: "Interact with PagerDuty Incidents",
        description: "Create a self-service action that creates and triggers PagerDuty incidents",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions","Webhook", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/interact-with-pagerduty-incidents",
    },
    {
        title: "Create a PagerDuty Service",
        description: "Create a self-service action that creates a PagerDuty service",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions","Webhook", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-pagerduty-service",
    },
    {
        title: "Escalate incident in PagerDuty",
        description: "Create a self-service action that escalates an incident in PagerDuty",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions", "Webhook", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/escalate-an-incident",
    },
    {
        title: "Resolve incident in PagerDuty",
        description: "Create a self-service action that resolves an incident in PagerDuty",
        tags: ["Self Healing Incidents", "PagerDuty", "GitHub", "Actions", "Webhook", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/resolve-incident",
    },
    {
        title: "Trigger a ServiceNow Incident",
        description: "Create a self-service action that triggers a ServiceNow incident",
        tags: ["Self Healing Incidents", "ServiceNow", "GitHub", "Actions", "Webhook", "Automations"],
        logos: ["ServiceNow", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/trigger-servicenow-incident",
    },
    {
        title: "Add tags to a SonarQube project",
        description: "Create a self-service action that adds tags to a SonarQube project",
        tags: ["Security", "SonarQube", "GitHub", "Actions","Webhook", "Automations"], 
        logos: ["SonarQube", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/add-tags-to-sonarqube-project",
    },
    {
        title: "Create an Application In Humanitec",
        description: "Create a self-service action that creates an application in Humanitec",
        tags: ["Humanitec", "GitHub", "Actions"],
        logos: ["Humanitec", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-humanitec-application",
    },
    {
        title: "Create a Workload Profile In Humanitec",
        description: "Create a self-service action that creates a workload profile in Humanitec",
        tags: ["Humanitec", "GitHub", "Actions"],
        logos: ["Humanitec", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-workload-profile",
    },
    {
        title: "Delete an Application In Humanitec",
        description: "Create a self-service action that deletes an application in Humanitec",
        tags: ["Humanitec", "GitHub", "Actions"],
        logos: ["Humanitec", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/delete-humanitec-application",
    },
    {
        title: "Deploy an Application In Humanitec",
        description: "Create a self-service action that deploys an application in Humanitec",
        tags: ["Humanitec", "GitHub", "Actions"],
        logos: ["Humanitec", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/deploy-humanitec-application",
    },
    {
        title: "EKS as a service (EKSaaS)",
        description: "Integrate Port and Upbound to manage EKS clusters using EKSaaS",
        tags: ["K8s for devs", "GitHub", "Actions"],
        logos: ["GitHub", "Kubernetes"],
        // category: "Getting started",
        link: "/guides/all/eks-as-a-service-action",
    },
    {
        title: "Create An AWS EC2 Instance",
        description: "Create a self-service action that creates an AWS EC2 instance using a Terraform template",
        tags: ["IaC for devs", "AWS", "Terraform", "Actions", "GitLab"],
        logos: ["AWS", "Terraform", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/create-an-ec2-instance-gitlab",
    },
    {
        title: "Add a Disk to an AWS EC2 Instance",
        description: "Create a self-service action that adds a disk to an AWS EC2 instance using a Terraform template",
        tags: ["IaC for devs", "AWS", "Terraform", "Actions", "GitLab"],
        logos: ["AWS", "Terraform", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/add-ec2-volume",
    },
    {
        title: "Create a Kubernetes namespace",
        description: "Create a self-service action that creates a Kubernetes namespace",
        tags: ["K8s for devs", "Actions", "GitLab"],
        logos: ["Kubernetes", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/create-k8s-namespace",
    },
    {
        title: "Automate AWS Account Creation with GitLab",
        description: "Create a self-service action that creates an AWS account",
        tags: ["Cloud access management", "Actions", "GitLab", "AWS"],
        logos: ["AWS", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/create-new-aws-account-gitlab",
    },
    {
        title: "Create a Jira Issue",
        description: "Create a self-service action that creates a Jira issue",
        tags: ["Jira", "Actions", "GitLab"],
        logos: ["Jira", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/report-a-bug-gitlab",
    },
    {
        title: "Scaffold BitBucket Repositories Using Cookiecutter",
        description: "Create a self-service action that scaffolds BitBucket repositories using a Cookiecutter template",
        tags: ["Jenkins", "BitBucket", "Actions"],
        logos: ["Jenkins", "BitBucket"],
        // category: "Getting started",
        link: "/guides/all/scaffold-bitbucket-using-cookiecutter",
    },
    {
        title: "Scaffold GitHub Repositories Using Cookiecutter",
        description: "Create a self-service action that scaffolds GitHub repositories using a Cookiecutter template",
        tags: ["Jenkins", "GitHub", "Actions"],
        logos: ["Jenkins", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/scaffold-github-using-cookiecutter",
    },
    {
        title: "Create Github pull request to add a Terraform resource",
        description: "Create a self-service action that adds a resource to a Terraform file and creates a pull request to add it to the repository",
        tags: ["IaC for devs", "Jenkins", "GitHub", "Actions"],
        logos: ["Jenkins", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/create-github-pull-request",
    },
    {
        title: "Deploy resource in Azure Cloud with Terraform",
        description: "Create a self-service action that deploys a storage account in Azure Cloud using a Terraform template",
        tags: ["IaC for devs", "Jenkins", "Terraform", "Azure", "Actions"],
        logos: ["Jenkins", "Terraform", "Azure"],
        // category: "Getting started",
        link: "/guides/all/deploy-azure-resource",
    },
    {
        title: "Scaffold Azure DevOps Repositories Using Cookiecutter",
        description: "Create a self-service action that scaffolds Azure DevOps repositories using a Cookiecutter template",
        tags: ["AzureDevops", "Actions"],
        logos: ["AzureDevops"],
        // category: "Getting started",
        link: "/guides/all/scaffold-repositories-using-cookiecutter",
    },
    {
        title: "Create Azure Resource with Terraform",
        description: "Create a self-service action that creates a storage account in Azure using a Terraform template",
        tags: ["IaC for devs", "AzureDevops", "Terraform", "Actions"],
        logos: ["AzureDevops", "Terraform"],
        // category: "Getting started",
        link: "/guides/all/create-azure-resource-ado",
    },
    {
        title: "Ingest dependencies from package.json file to service",
        description: "Ingest dependencies from a package.json file and relate them to the corresponding service entities",
        tags: ["GitHub"],
        logos: ["GitHub"],
        // category: "Getting started",
        link: "/guides/all/ingest-dependencies-from-package-json-to-service",
    },
    {
        title: "Manage Kubernetes namespaces via a Port workflow",
        description: "Chain actions and automations to automate the deletion of Kubernetes namespaces",
        tags: ["K8s for devs", "Approval workflow", "GitLab", "Actions", "Automations"],
        logos: ["Kubernetes", "GitLab"],
        // category: "Getting started",
        link: "/guides/all/manage-kubernetes-namespaces",
    },
    {
        title: "Sync Service Entities to incident.io",
        description: "Create a GitHub action that syncs service entities to your incident.io catalog",
        tags: ["Self Healing Incidents","GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/sync-service-entities-to-incident-io",
    },
    {
        title: "Ingest cloud resources with Datadog",
        description: "Learn how to ingest cloud resources using Datadog in Port, enhancing visibility and performance monitoring",
        tags: ["Cloud access management", "Datadog"],
        logos: ["Datadog"],
        link: "/guides/all/ingest-cloud-resources-using-datadog",
    },
    // {
    //     title: "Track DORA Metrics",
    //     description: "Setup DevOps Research and Assessment (DORA) metrics within your organization in PORT",
    //     tags: ["Engineering Intelligence","GitHub","GitLab","AzureDevops","Dashboards"],
    //     logos: ["Git"],
    //     link: "/guides/all/setup-dora-metrics",
    // },
    {
        title: "Ingest a swagger.json file into your catalog",
        description: "Ingest API paths from a `swagger.json` file in a GitHub repository into Port",
        tags: ["API catalog", "GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/ingest-swagger-paths-into-your-catalog",
    },
    {
        title: "Ingest Checkmarx KICS scan results into your catalog",
        description: "Ingests Checkmarx KICS scan results in your Checkmarx KICS file using Port's GitHub file ingesting feature",
        tags: ["Security", "Checkmarx", "GitHub"],
        logos: ["Checkmarx", "GitHub"],
        link: "/guides/all/ingest-checkmarx-kics-scan-into-your-catalog"
    },
    {
        title: "Ingest Javascript packages into your catalog",
        description: "Ingests all Javascript packages in `package.json` file using Port's GitHub file ingesting feature",
        tags: ["Dependency management", "GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/ingest-javascript-packages-into-your-catalog"
    },
    {
        title: "Ingest software bills of materials (SBOMs) into your catalog",
        description: "Ingests software bill of material (SBOM) in your `SBOM.json` or `SBOM.xml` file using Port's GitHub file ingesting feature",
        tags: ["Security", "GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/ingest-software-bill-of-materials-sbom-into-your-catalog"
    },
    {
        title: "Ingest Trivy vulnerabilities into your catalog",
        description: "Ingests Trivy vulnerabilities in your Trivy scan results file using Port's GitHub file ingesting feature",
        tags: ["Security", "Trivy", "GitHub"],
        logos: ["Trivy", "GitHub"],
        link: "/guides/all/ingest-trivy-vulnerabilities-into-your-catalog"
    },
    {
        title: "Ingest cloud resources using New Relic",
        description: "Ingest cloud resources from your New Relic environment into Port",
        tags: ["New Relic"],
        logos: ["New Relic"],
        // category: "Getting started",
        link: "/guides/all/ingest-cloud-resources-using-newrelic",
    },
    {
        title: "Ingest vulnerability alerts from Orca Security",
        description: "Ingest vulnerability alerts from Orca Security using a custom webhook integration",
        tags: ["Security", "Webhook"],
        logos: ["Webhook"],
        link: "/guides/all/ingest-vulnerability-alerts-from-orca-security-using-a-custom-webhook-integration"
    },
    {
        title: "Measure pull request standards",
        description: "Implement working agreements and measure pr standards",
        tags: ["Engineering Intelligence", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/working_agreements_and_measuring_pr_standards"
       
    },
    {
        title: "Automatically approve actions using an automation",
        description: "Set up automated approvals for self service actions",
        tags: ["Cloud access management", "Actions", "Automations"],
        logos: ["Slack"],
        link: "/guides/all/automatically-approve-action-using-automation"
    },
    {
        title: "Copy ADO Pipeline Template to Target Repo",
        description: "Create a self-service action that copies an AzureDevops pipeline template to a target repository",
        tags: ["AzureDevops", "Actions"],
        logos: ["AzureDevops"],
        link: "/guides/all/copy-pipeline-template-to-target-repo",

    },
    {
        title: "Track SLOs and SLIs for services",
        description: "Track service level objectives (SLOs) and service level indicators (SLIs) for services in Port",
        tags: ["Engineering Intelligence", "New Relic", "Dashboards"],
        logos: ["New Relic"],
        link: "/guides/all/track-slos-and-slis-for-services"
    },
    {
        title: "Ingest security issues from .sarif files to services",
        description: "Ingest .sarif files and relate them to the corresponding service entities",
        tags: ["Security", "GitHub"],
        logos: ["GitHub"],
        link: "/guides/all/ingest-security-issues-from-sarif-files-to-services",
    },
    {
        title: "Set up announcements in your portal",
        description: "Create components to send announcements to members in your portal",
        tags: ["Actions", "Dashboards"],
        logos: ["Actions"],
        link: "/guides/all/setup-portal-announcements",
    },
    // {
    //     title: "Set up DORA Metrics benchmark",
    //     description: "Track and improve engineering performance by setting up DORA metrics benchmark",
    //     tags: ["Engineering Intelligence","Scorecards","Dashboards"],
    //     logos: ["Git"],
    //     link: "/guides/all/setup-dora-metrics-benchmark"
    // },
    {
        title: "Manage service deployments using GitLab and ServiceNow", 
        description: "Create a chain of self-service actions that deploy a service using GitLab and ServiceNow",
        tags: ["Approval workflow", "ServiceNow", "GitLab", "Actions", "Automations"],
        logos: ["ServiceNow", "GitLab"],
        link: "/guides/all/approval-workflow-for-gitlab-deployment"
    },
    {
        title: "Assign teams to monitored entities", 
        description: "Configure your Dynatrace data sources to map entities to teams",
        tags: ["Dynatrace"],
        logos: ["Dynatrace"],
        link: "/guides/all/connect-dynatrace-team-with-entities"
    },
    // {
    //     title: "Create surveys in your portal",
    //     description: "Create surveys to collect feedback from your developers",
    //     tags: ["Engineering Intelligence", "Actions", "Dashboards"],
    //     logos: ["Engineering Intelligence"],
    //     link: "/guides/all/create-surveys",
    // },
    {
        title: "Ingest Slack channels data with Airbyte, S3 & webhook",
        description: "Send Slack channel data to S3 with Airbyte, then ingest it into Port via a custom webhook integration",
        tags: ["Slack", "AWS", "Webhook"],
        logos: ["Slack", "AWS", "Webhook"],
        link: "/guides/all/ingest-slack-data-via-airbyte-s3-and-webhook"
    },
    {
        title: "Ingest HiBob data with Airbyte, S3 & webhook",
        description: "Send Hibob data to S3 with Airbyte, then ingest it into Port via a custom webhook integration",
        tags: ["AWS", "Webhook"],
        logos: ["AWS", "Webhook"],
        link: "/guides/all/ingest-hibob-data-via-airbyte-s3-and-webhook"
    },
    {
        title: "Ingest Okta data with Airbyte, S3 & webhook",
        description: "Send Okta data to S3 with Airbyte, then ingest it into Port via a custom webhook integration",
        tags: ["AWS", "Webhook"],
        logos: ["AWS", "Webhook"],
        link: "/guides/all/ingest-okta-data-via-airbyte-s3-and-webhook"
    },

    {
        title: "Create a Linear issue",
        description: "Create a self-service action that creates a Linear issue",
        tags: ["Linear", "Actions", "Webhook", "Automations"],
        logos: ["Linear", "Webhook"],
        link: "/guides/all/open-linear-issue",
    },
    {
        title: "Create an incident.io Incident",
        description: "Create a self-service action that creates an incident.io incident",
        tags: ["Self Healing Incidents", "Actions", "Webhook", "Automations"],
        logos: ["IncidentIO", "Webhook"],
        link: "/guides/all/create-incident-io-incident",
    },
    {
        title: "Manage FireHydrant incidents",
        description: "Create a self-service action that manages FireHydrant incidents",
        tags: ["Self Healing Incidents", "FireHydrant", "Actions", "Webhook"],
        logos: ["FireHydrant", "GitHub"],
        // category: "Getting started",
        link: "/guides/all/manage-firehydrant-incidents",
    },
    {
        title: "Remediate vulnerabilities with AI",
        description: "Use Port AI agents with Claude Code to remediate security vulnerabilities and trigger automated fixes",
        tags: ["Security", "Claude Code", "GitHub", "AI"],
        logos: ["AI", "Snyk", "Wiz"],
        link: "/guides/all/remediate-vulnerability-with-ai",
    },
    {
        title: "Monitor integrations",
        description: "Monitor and manage your Port Ocean integrations",
        tags: [],
        logos: ["Webhook"],
        link: "/guides/all/manage-integrations",
    },
    {
        title: "Report a Jira bug from a New Relic alert",
        description: "Create a self-service action that reports a Jira bug from a New Relic alert",
        tags: ["Jira","New Relic","Actions","Webhook"],
        logos: ["Jira","New Relic"],
        link: "/guides/all/create-jira-issue-from-newrelic",
    },
    {
        title: "Create a PagerDuty incident from a New Relic alert",
        description: "Create a self-service action that creates a PagerDuty incident from a New Relic alert",
        tags: ["PagerDuty","New Relic","Actions","Webhook"],
        logos: ["PagerDuty","New Relic"],
        link: "/guides/all/create-pagerduty-incident-from-newrelic-alert",
    },
    {
        title: "Set up the Task Manager AI agent",
        description: "Set up a Task Manager AI agent to help developers track and manage tasks efficiently",
        tags: ["AI", "Jira", "GitHub", "Actions", "Automations"],
        logos: ["AI", "Jira", "GitHub"],
        link: "/guides/all/setup-task-manager-ai-agent",
    },
    {
        title: "Set up the Incident Manager AI agent",
        description: "Set up an AI agent that helps developers track and manage incidents efficiently",
        tags: ["Self Healing Incidents", "AI", "PagerDuty", "Slack"],
        logos: ["AI", "PagerDuty", "Slack"],
        link: "/guides/all/setup-incident-manager-ai-agent",
    },
    {
        title: "Enrich tasks with AI-powered context",
        description: "Set up an AI agent that provides contextual information and insights to task assignees",
        tags: ["Autonomous Ticket Resolution","AI", "Jira", "GitHub", "Actions", "Automations"],
        logos: ["AI", "Jira", "GitHub"],
        link: "/guides/all/enrich-tasks-with-ai",
    },
    {
        title: "Enrich pull requests using AI",
        description: "Set up an AI agent that automatically comments on pull requests with additional context",
        tags: ["Autonomous Ticket Resolution", "AI", "GitHub", "Jira", "PagerDuty"],
        logos: ["AI", "GitHub", "Jira"],
        link: "/guides/all/setup-pr-enricher-ai-agent",
    },
    {
        title: "Set up the Platform Request Triage AI agent",
        description: "Set up an AI agent that helps developers submit and track requests to the platform team",
        tags: ["AI", "Slack", "Actions", "Automations"],
        logos: ["AI", "Slack"],
        link: "/guides/all/setup-platform-request-triage-ai-agent",
    },
    {
        title: "Set up the Service Explorer AI agent",
        description: "Set up an AI agent with MCP server backend mode that helps developers explore and understand your software catalog",
        tags: ["AI", "GitHub"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/setup-service-explorer-ai-agent",
    },
    {
        title: "Create a GitHub issue",
        description: "Create a self-service action that creates a GitHub issue",
        tags: ["GitHub", "Actions", "Webhook"],
        logos: ["GitHub"],
        link: "/guides/all/open-github-issue",
    },
    {
        title: "Remind service owners to update their catalog data",
        description: "Set up a workflow that notifies service owners to ensure service catalog data is up to date",
        tags: ["GitHub", "Actions", "Webhook", "Automations"],
        logos: ["GitHub"],
        link: "/guides/all/verify-service",
    },
    {
        title: "Enforce Branch Protection Rules with Scorecards",
        description: "Create a scorecard that tracks branch protection rules and enforces security policies",
        tags: ["Security", "GitHub", "Scorecards"],
        logos: ["GitHub"],
        link: "/guides/all/setup-branch-protection-rules",
    },
    {
        title: "Ignore Snyk Vulnerability",
        description: "Create a self-service action that ignores a Snyk vulnerability",
        tags: ["Security","Snyk","Actions","Webhook"],
        logos: ["Snyk"],
        link: "/guides/all/ignore-snyk-vulnerability",
    },
    {
        title: "Enforce code maturity with GitLab file search",
        description: "Create a scorecard that tracks GitLab code maturity based on file existence",
        tags: ["Security", "GitLab", "Scorecards"],
        logos: ["GitLab"],
        link: "/guides/all/track-gitlab-project-maturity-with-scorecards",
    },
    {
        title: "Trigger Spacelift stack",
        description: "Create a self-service action that triggers a Spacelift stack to automate infrastructure workflows",
        tags: ["IaC for devs", "Actions"],
        logos: ["Git"],
        link: "/guides/all/trigger-spacelift-stack",
    },
    {
        title: "Track health of Jira projects using scorecards",
        description: "Create a scorecard to track the health of Jira projects",
        tags: ["Jira", "Scorecards"],
        logos: ["Jira",],
        link: "/guides/all/track-health-of-jira-projects",
    },
    {
        title: "Automatically create Jira issue from Datadog alert",
        description: "Create an automation that creates a Jira issue from a Datadog alert",
        tags: ["Self Healing Incidents", "Jira", "Datadog", "Automations"],
        logos: ["Jira", "Datadog"],
        link: "/guides/all/create-jira-issue-from-datadog-alert",
    },
    {
        title: "Automatically create Jira issue from Snyk vulnerability",
        description: "Create an automation that creates a Jira issue from a Snyk vulnerability",
        tags: ["Security", "Jira", "Snyk", "Automations", "Webhook"],
        logos: ["Jira", "Snyk"],
        link: "/guides/all/create-jira-issue-from-snyk-vulnerability",
    },
    {
        title: "Notify users upon approval of self-service actions",
        description: "Create an automation that notifies users when a self-service action is approved/declined",
        tags: ["Approval workflow", "Slack", "Actions", "Automations"],
        logos: ["Slack"],
        link: "/guides/all/notify-users-upon-approval-of-action",
    },
    {
        title: "Visualize your GitHub repository and developer activity",
        description: "Create a dashboard that visualizes your GitHub repository and developer activity",
        tags: ["Engineering Intelligence", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/visualize-your-github-repository-activity",
    },
    {
        title: "Visualize your Wiz vulnerabilities",
        description: "Create a dashboard that visualizes your Wiz vulnerabilities",
        tags: ["Security", "Wiz", "Dashboards"],
        logos: ["Wiz"],
        link: "/guides/all/visualize-your-wiz-vulnerabilities",
    },
    {
        title: "Visualize your GitHub dependency security alerts",
        description: "Create a dashboard that visualizes your GitHub dependency security alerts using dependabot alerts",
        tags: ["Security", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/visualize-your-github-dependabot-alerts",
    },
    {
        title: "Ingest Slack channels data with Fivetran, S3 & webhook",
        description: "Send Slack channel data to S3 with Fivetran, then ingest it into Port via a custom webhook integration",
        tags: ["Slack", "AWS", "Webhook"],
        logos: ["Slack", "AWS", "Webhook"],
        link: "/guides/all/ingest-slack-data-via-fivetran-s3-and-webhook"
    },
    {
        title: "Automate admin role assignment",
        description: "Set up automated user role assignment when they are added to Admins group.",
        tags: ["Security", "Automations", "Access controls"],
        logos: ["Automations"],
        link: "/guides/all/automate-user-role-update",
    },
    {
        title: "Automatically set relations between entities with automation",
        description: "Set up automations to set relations between entities based on integrations metadata",
        tags: ["Automations", "GitHub"],
        logos: ["Automations"],
        link: "/guides/all/automatically-set-relations-between-entities-with-automation",
    },
    {
        title: "Manage and visualize your AWS S3 buckets and RDS instances",
        description: "Create a dashboard that manages and visualizes your AWS S3 buckets and RDS instances",
        tags: ["Security", "AWS", "GitHub", "Dashboards"],
        logos: ["AWS", "GitHub",],
        link: "/guides/all/visualize-your-aws-storage-configuration",
    },
    {
        title: "Interact with ServiceNow records and delete incidents",
        description: "Create a self-service action that interacts with ServiceNow records and delete ServiceNow incidents",
        tags: ["Self Healing Incidents", "ServiceNow", "Actions","Webhook","Automations"],
        logos: ["ServiceNow"],
        link: "/guides/all/interact-with-servicenow",
    },
    {
        title: "Visualize your GitHub identity and access management",
        description: "Create a dashboard that visualizes your GitHub identity and access management",
        tags: ["Security", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/visualize-your-github-identity-and-access-management",
    },
    {
        title: "Visualize Okta security insights",
        description: "Build a security analytics dashboard for Okta identity and access management",
        tags: ["Security", "Okta", "Dashboards"],
        logos: ["Okta"],
        link: "/guides/all/visualize-okta-security-insights",
    },
    {
        title: "Auto-label your GitHub PRs with Sonar Scans",
        description: "Create an automation that applies labels to GitHub pull requests based on SonarQube scans",
        tags: ["Security", "GitHub", "SonarQube", "Automations"],
        logos: ["GitHub", "SonarQube"],
        link: "/guides/all/apply-labels-to-github-pr-based-on-sonar-scans",
    },
    {
        title: "Create an Azure DevOps Work Item",
        description: "Create a self-service action that creates an Azure DevOps work item",
        tags: ["AzureDevops", "Actions"],
        logos: ["AzureDevops", "Webhook"],
        link: "/guides/all/create-azure-devops-work-item",
    },    
    {
        title: "Deploy a service using AWS CodeDeploy",
        description: "Create a self-service action that deploys a service using AWS CodeDeploy",
        tags: ["AWS", "Actions"],
        logos: ["AWS", "Webhook"],
        link: "/guides/all/deploy-service-using-aws-codedeploy",
    },
    {
        title: "Auto approve and merge Dependabot PRs",
        description: "Create an automation that approves and merges Dependabot pull requests",
        tags: ["Autonomous Ticket Resolution", "GitHub", "Automations"],
        logos: ["GitHub"],
        link: "/guides/all/auto-approve-and-merge-dependabot-prs",
    },
    {
        title: "Send TypeForm survey results to Port",
        description: "Create a webhook integration that sends TypeForm survey results to Port",
        tags: ["Engineering Intelligence", "Webhook"],
        logos: ["Webhook"],
        link: "/guides/all/send-typeform-survey-results-to-port",
    },
    {
        title: "Visualize and manage your EC2 instances",
        description: "Create a dashboard that visualizes and manages your AWS EC2 instances",
        tags: ["Cloud access management", "AWS", "GitHub", "Dashboards"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/visualize-and-manage-aws-ec2-instances",
    },
    {
        title: "Visualize and manage your ServiceNow incidents",
        description: "Create a dashboard that visualizes and manages your ServiceNow incidents",
        tags: ["Self Healing Incidents", "ServiceNow", "Actions", "Dashboards"],
        logos: ["ServiceNow"],
        link: "/guides/all/visualize-and-manage-servicenow-incidents",
    },
    {
        title: "Visualize and manage your GitLab deployments",
        description: "Create a dashboard that visualizes and manages your GitLab deployments",
        tags: ["GitLab", "Actions", "Dashboards"],
        logos: ["GitLab"],
        link: "/guides/all/visualize-and-manage-gitlab-deployments",
    },
    {
        title: "Visualize and manage your Azure DevOps deployments",
        description: "Create a dashboard that visualizes and manages your Azure DevOps deployments",
        tags: ["AzureDevops", "Actions", "Dashboards"],
        logos: ["AzureDevops"],
        link: "/guides/all/visualize-and-manage-azure-devops-deployments",
    },
    {
        title: "Visualize and manage your Statuspage incidents and components",
        description: "Create a dashboard that visualizes and manages your Statuspage incidents and components",
        tags: ["Self Healing Incidents", "StatusPage", "Actions", "Dashboards"],
        logos: ["StatusPage"],
        link: "/guides/all/visualize-and-manage-statuspage-incidents",
    },
    {
        title: "Manage PagerDuty on-call schedules",
        description: "Track on-call engineers across different teams and services with dashboards and self-service actions",
        tags: ["Self Healing Incidents", "PagerDuty", "Actions", "Dashboards"],
        logos: ["PagerDuty"],
        link: "/guides/all/manage-pagerduty-on-call-schedules",
    },
    {
        title: "Manage and visualize your LaunchDarkly feature flags",
        description: "Create a comprehensive feature flag management system to create, toggle, and archive flags",
        tags: ["Feature flag management","Launchdarkly", "Actions", "Webhook", "Automations"],
        logos: ["Launchdarkly"],
        link: "/guides/all/manage-and-visualize-your-launchdarkly-feature-flags",
    },
    {
         title: "Manage and visualize your PagerDuty incidents",
          description: "Manage your PagerDuty incidents with self-service actions and create dashboards for visualization",
          tags: ["Self Healing Incidents", "PagerDuty", "Actions", "Dashboards"],
          logos: ["PagerDuty"],
          link: "/guides/all/manage-and-visualize-pagerduty-incidents",
    },
    {

        title: "Manage and visualize ECS Tasks",
        description: "Select from your clusters and services, and easily scale tasks up or down",
        tags: ["Cloud access management", "AWS", "GitHub", "Actions", "Dashboards"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/manage-and-visualize-ecs-tasks",
    },
    {
        title: "Manage and visualize your AWS SQS queues",
        description: "Manage your AWS SQS queues with self-service actions and create dashboards for visualization",
        tags: ["Cloud access management", "AWS", "GitHub", "Dashboards"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/manage-and-visualize-aws-sqs-queues",
    },
    {
        title: "Manage and visualize your Jira issues",
        description: "Create a comprehensive Jira issue management system to create, update, and archive issues",
        tags: ["Agentic Work Management", "Jira", "Actions", "Dashboards"],
        logos: ["Jira"],
        link: "/guides/all/manage-and-visualize-jira-issues",
    },
    {
        title: "Add RCA context to AI agents",
        description: "Enhance AI agents with Root Cause Analysis context",
        tags: ["Self Healing Incidents", "AI", "Actions"],
        logos: ["AI"],
        link: "/guides/all/add-rca-context-to-ai-agents",
    },
    {
        title: "Manage your EKS clusters",
        description: "Create self-service actions that manage your EKS clusters",
        tags: ["Cloud access management", "AWS", "GitHub", "Actions"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/manage-your-eks-clusters",
    },
    {
        title: "Manage and visualize your ACM certificates",
        description: "Create a comprehensive certificate management system to create, renew, and delete certificates",
        tags: ["Security", "AWS", "GitHub", "Dashboards"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/manage-and-visualize-acm-certificates",
    },
    {
        title: "Manage and visualize your GCP Compute Engine instances",
        description: "Create a dashboard that manages and visualizes your GCP Compute Engine instances",
        tags: ["Cloud access management", "GCP", "GitHub", "Dashboards"],
        logos: ["GCP", "GitHub"],
        link: "/guides/all/manage-and-visualize-gcp-compute-engine-instances",
    },
    {
        title: "Manage and visualize your Azure web apps",
        description: "Create a comprehensive web app management system to start, stop and restart web apps",
        tags: ["Cloud access management", "Azure", "GitHub", "Dashboards"],
        logos: ["Azure", "GitHub"],
        link: "/guides/all/manage-and-visualize-azure-web-apps",
    },
    {
        title: "Manage your Azure Virtual Machines",
        description: "Create a comprehensive VM management system to start, deallocate and restart virtual machines",
        tags: ["Cloud access management", "Azure", "GitHub", "Dashboards"],
        logos: ["Azure", "GitHub"],
        link: "/guides/all/manage-and-visualize-azure-virtual-machines",
    },
    {
        title: "Manage your AWS Autoscaling Groups",
        description: "Create a comprehensive autoscaling group management system to scale up and down",
        tags: ["Cloud access management", "AWS", "GitHub", "Dashboards"],
        logos: ["AWS", "GitHub"],
        link: "/guides/all/manage-and-visualize-aws-autoscaling-groups",
    },
    {
        title: "Track leaked GitHub secrets in Port",
        description: "Create a webhook integration that tracks leaked GitHub secrets in Port",
        tags: ["Security", "GitHub", "Webhook"],
        logos: ["GitHub", "Webhook"],
        link: "/guides/all/track-leaked-github-secrets-in-port",
    },
    {
        title: "Track and show MTBF for services",
        description: "Track Mean Time Between Failures (MTBF) for your services to measure reliability and identify improvement opportunities",
        tags: ["Engineering Intelligence", "PagerDuty", "Dashboards", "Scorecards"],
        logos: ["PagerDuty"],
        link: "/guides/all/track-and-show-mtbf-for-services",
    },
    {
        title: "Manage your Kubernetes deployments",
        description: "Create a comprehensive Kubernetes deployment management system to restart deployments and delete pods",
        tags: ["K8s for devs", "Kubernetes", "GitHub", "Actions"],
        logos: ["Kubernetes", "GitHub"],
        link: "/guides/all/manage-your-kubernetes-deployment",
    },
    {
        title: "Pull GitHub metrics and build visualizations",
        description: "Collect comprehensive GitHub metrics and build powerful visualizations to track engineering performance",
        tags: ["Engineering Intelligence", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/pull-github-metrics-and-build-visualizations",
    },
    {
        title: "Visualize and manage your GitHub deployments",
        description: "Create a dashboard that visualizes and manages your GitHub deployments",
        tags: ["GitHub", "Actions", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/visualize-and-manage-github-deployments",
    },
    {
        title: " Create an actions ROI dashboard",
        description: "Create a dashboard that tracks the ROI of actions in Port",
        tags: [ "Actions", "Dashboards", "Automations"],
        logos: ["Actions", "Automations"],
        link: "/guides/all/create-roi-dashboard",
    },
    {
        title: "Send Slack messages using Port's Slack app and automations",
        description: "Learn how to send Slack messages to users using Port's Slack app and automations",
        tags: ["Automations", "Slack"],
        logos: ["Slack"],
        link: "/guides/all/send-slack-message-to-user",
    },
    {

        title: "Map Git users to Port user accounts",
        description: "Automatically map Git users to their Port user accounts for seamless integration",
        tags: ["Git", "GitHub", "GitLab", "AzureDevops", "Automations"],
        logos: ["Git"],
        link: "/guides/all/map-git-users-to-port-accounts",
    },
    {
        title: "Ingest and map HiBob users to Port user accounts",
        description: "Ingest and map HiBob users to Port user accounts for seamless integration",
        tags: ["Actions", "Automations", "Webhook"],
        logos: ["Webhook"],
        link: "/guides/all/map-hibob-users-to-port-accounts",
    },
    {
        title: "Map Jira users to Port user accounts",
        description: "Automatically map Jira users to their Port user accounts for seamless integration",
        tags: ["Agentic Work Management", "Jira", "Automations"],
        logos: ["Jira"],
        link: "/guides/all/map-jira-users-to-port-accounts",
    },
    {
        title: "Ingest and map Slack users to Port user accounts",
        description: "Ingest and map Slack users to Port user accounts for seamless integration",
        tags: ["Slack",  "Actions", "Automations","Webhook"],
        logos: ["Slack", "Webhook"],
        link: "/guides/all/map-slack-users-to-port-accounts",
    },
    {
        title: "Ingest and map ServiceNow users to Port user accounts",
        description: "Ingest and map ServiceNow users to Port user accounts for seamless integration",
        tags: ["ServiceNow", "Actions", "Automations", "Webhook"],
        logos: ["ServiceNow", "Webhook"],
        link: "/guides/all/map-servicenow-users-to-port-accounts",
    },
    {
        title: "Generate incident updates with AI",
        description: "Generate incident updates with AI and send them to Slack",
        tags: ["Self Healing Incidents", "AI", "Automations"],
        logos: ["AI", "Slack", "PagerDuty"],
        link: "/guides/all/generate-incident-updates-with-ai",
    },
    {
        title: "Map PRs to services in a monorepo",
        description: "Automatically map GitHub pull requests to services in a monorepo using file path analysis",
        tags: ["GitHub", "Automations"],
        logos: ["GitHub"],
        link: "/guides/all/map-prs-to-services-in-monorepo",
    },
    {
        title: "Trigger GitHub Copilot from Port",
        description: "Learn how to set up GitHub Copilot triggers from Port to enable AI-powered coding assistance",
        tags: ["Autonomous Ticket Resolution", "Github Copilot", "AI", "Actions"],
        logos: ["GitHub", "AI"],
        link: "/guides/all/trigger-github-copilot-from-port",
    },
    {
        title: "Trigger Google Gemini Assistant from Port",
        description: "Learn how to trigger Google Gemini Assistant from Port to enable AI-powered coding assistance in your development workflow",
        tags: ["Autonomous Ticket Resolution", "GitHub", "AI", "Actions"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/trigger-gemini-assistant-from-port",
    },
    {
        title: "Summarize Zendesk tickets with AI",
        description: "Use Port's remote MCP to fetch ticket context and generate AI summaries on demand",
        tags: ["AI", "Actions", "Webhook"],
        logos: ["AI", "Webhook"],
        link: "/guides/all/generate-zendesk-ticket-summaries-with-ai",
    },
    {
        title: "Automatically resolve tickets with coding agents",
        description: "Learn how to create an AI agent that automatically resolves tickets with coding agents",
        tags: ["Autonomous Ticket Resolution", "Jira", "Github Copilot", "AI"],
        logos: ["Jira", "GitHub", "AI"],
        link: "/guides/all/automatically-resolve-tickets-with-coding-agents",
    },
    {
        title: "Auto-fix services when scorecards degrade",
        description: "Learn how to use Port's AI capabilities to detect scorecard degradation and automatically use a coding agent like GitHub Copilot to fix it",
        tags: ["Autonomous Ticket Resolution", "AI", "GitHub", "Scorecards"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/self-heal-scorecards-with-ai",
    },
    {
        title: "Track AI-driven pull requests",
        description: "Track AI-driven pull requests and visualize them in a dashboard",
        tags: ["Engineering Intelligence", "Github Copilot", "Dashboards", "AI"],
        logos: ["GitHub"],
        link: "/guides/all/track-ai-driven-pull-requests",
    },
    {
        title: "Visualize GitHub Copilot metrics",
        description: "Create dashboards to monitor GitHub Copilot usage, track acceptance rates, and measure team productivity",
        tags: ["Engineering Intelligence", "Github Copilot", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/visualize-github-copilot-metrics",
    },
    {
        title: "Trigger Claude Code from Port",
        description: "Learn how to trigger Claude Code from Port to enable AI-powered coding assistance",
        tags: ["Autonomous Ticket Resolution", "Claude Code", "AI", "Actions"],
        logos: ["AI", "Claude Code"],
        link: "/guides/all/trigger-claude-code-from-port",
    },
    {
        title: "Build an OWASP Top 10 Scorecard",
        description: "Build an OWASP Top 10 security scorecard in Port using vulnerability data from Snyk",
        tags: ["Security", "Scorecards", "Snyk"],
        logos: ["Snyk"],
        link: "/guides/all/owasp-top-10-scorecard",
    },
    {
        title: "PCI DSS code security scorecard",
        description: "Continuously track compliance with PCI DSS requirements using code scans and vulnerability data",
        tags: ["Security", "Scorecards", "Snyk"],
        logos: ["Snyk"],
        link: "/guides/all/setup-pci-dss-code-compliance",
    },
    {
        title: "Enforce AI coding security standards",
        description: "Learn how to enforce AI coding security standards in your organization",
        tags: ["Autonomous Ticket Resolution", "AI", "GitHub", "Scorecards"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/enforce-ai-coding-security-standards",
    },
    {
        title: "Find internal documentation with AI",
        description: "Find internal documentation using AI by storing documentation as entities in your Port catalog",
        tags: ["Autonomous Ticket Resolution","AI"],
        logos: ["AI"],
        link: "/guides/all/find-internal-documentation-with-ai",
    },
    {
        title: "Heal unhealthy k8s pods",
        description: "Detect unhealthy Kubernetes pods and automatically trigger remediation actions using Port AI",
        tags: ["K8s for devs", "AI", "Kubernetes", "Actions", "Automations"],
        logos: ["AI", "Kubernetes"],
        link: "/guides/all/heal-unhealthy-k8s-pods",
    },
    {
        title: "Manage AI instructions with Port",
        description: "Learn how to centralize AI instructions in Port and automatically sync them to GitHub repositories",
        tags: ["Autonomous Ticket Resolution", "GitHub", "AI",  "Automations"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/manage-ai-instructions",
    },
    {
        title: "Manage MCP Server Registry",
        description: "Build a centralized MCP server registry with governance, discovery, and automated metadata extraction",
        tags: ["AI", "Actions", "Automations", "Access controls"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/manage-mcp-registry",
      
    },
    {
        title: "Auto-enhance PR descriptions with AI",
        description: "Automatically generate comprehensive, template-compliant PR descriptions using Claude Code",
        tags: ["SDLC", "GitHub", "AI", "Automations"],
        logos: ["AI", "GitHub", "Claude Code"],
        link: "/guides/all/auto-enhance-pr-descriptions-with-ai",
    },
    {
        title: "Auto-generate GitHub workflow documentation",
        description: "Automatically generate and maintain human-readable documentation for GitHub Actions workflows using Port's AI agents and automation system",
        tags: ["AI", "GitHub", "Automations"],
        logos: ["AI", "GitHub"],
        link: "/guides/all/ai-powered-github-workflow-documentation",
    },
    {
        title: "Streamline IaC with AI",
        description: "Use Port AI agents to automate IaC provisioning and management",
        tags: ["IaC for devs", "Github Copilot", "AI", "Actions"],
        logos: ["AI", "AWS"],
        link: "/guides/all/streamline-iac-with-ai",
    },
    {
        title: "Auto-remediate insecure cloud resources with AI",
        description: "Learn how to use Port's AI capabilities to detect insecure cloud resources and automatically use a coding agent like Claude Code to fix it",
        tags: ["Cloud access management", "AI", "GitHub", "Claude Code"],
        logos: ["AI", "Claude Code"],
        link: "/guides/all/auto-remediate-insecure-cloud-resources-with-ai",
    },
    {
        title: "Improve specifications with Port AI",
        description: "Learn how to implement an AI-powered triage system that automatically evaluates tickets, enriches them with missing context, and ensures only well-defined tasks reach your coding agents",
        tags: ["Autonomous Ticket Resolution", "AI", "Claude Code", "Jira"],
        logos: ["AI", "Claude Code", "Jira"],
        link: "/guides/all/triage-tickets-to-coding-agents",
    },
    {
        title: "Query DORA metrics using Port MCP",
        description: "Query DORA metrics using natural language commands directly from your IDE with Port's MCP server",
        tags: ["Engineering Intelligence", "AI"],
        logos: ["AI"],
        link: "/guides/all/query-dora-metrics-using-port-mcp",
    },
    {
        title: "Define scorecards with AI",
        description: "Design scorecards that AI agents can query to evaluate compliance, security posture, and production readiness",
        tags: ["AI", "Scorecards"],
        logos: ["AI"],
        link: "/guides/all/build-port-scorecards-with-mcp",
    },
    {
        title: "Build your software catalog with MCP",
        description: "Use Port's MCP server to build and manage your software catalog through natural language conversations with AI.",
        tags: ["AI"],
        logos: ["AI"],
        link: "/guides/all/build-port-data-model-with-mcp",
    },
    {
        title: "Migrate repositories from Bitbucket to GitHub",
        description: "Migrate repositories from Bitbucket to GitHub using Port self-service actions and GitHub Actions",
        tags: [ "BitBucket", "GitHub", "Actions", "Scorecards"],
        logos: ["BitBucket", "GitHub"],
        link: "/guides/all/migrate-project-from-bibucket-to-github",
    },
    {
        title: "Orchestrate incident response with AI",
        description: "Orchestrate incident response with AI using Port's AI agents and automations",
        tags: ["Self Healing Incidents", "AI", "Jira", "PagerDuty", "Slack"],
        logos: ["Jira", "PagerDuty", "Slack"],
        link: "/guides/all/orchestrate-incident-response-with-ai",
    },
    {
        title: "Generate incident updates with n8n and Port",
        description: "Use Port as a context lake in n8n workflows to automatically generate contextual incident updates and send enriched Slack notifications with relevant technical context",
        tags: ["Self Healing Incidents", "n8n", "Slack", "AI"],
        logos: ["n8n", "Slack"],
        link: "/guides/all/generate-incident-updates-with-n8n-and-port",
    },
    {
        title: "Remediate security vulnerability with n8n and Port AI",
        description: "Remediate security vulnerabilities with n8n and Port AI using Port's AI agents and automations",
        tags: ["Security", "n8n", "Slack", "AI"],
        logos: ["n8n", "Slack"],
        link: "/guides/all/remediate-vulnerability-with-n8n-and-port",
    },
    {
        title: "Automatically resolve tickets with n8n and Port context",
        description: "Automatically resolve tickets with n8n and Port context using Port's AI agents and automations",
        tags: ["Autonomous Ticket Resolution", "n8n", "AI", "Jira"],
        logos: ["n8n", "Jira", "GitHub"],
        link: "/guides/all/automatically-resolve-tickets-with-n8n-port-context",
    },
    {
        title: "Build actions and automations with AI",
        description: "Create self-service actions and automations optimized for MCP, enabling AI agents to execute workflows and chain complex operations",
        tags: ["AI", "Actions", "Automations"],
        logos: ["AI"],
        link: "/guides/all/build-port-actions-with-mcp",
    },
    {
        title: "RBAC for AI agents with n8n and Port",
        description: "Implement role-based access control (RBAC) for multi-agent systems using Port and n8n, enabling dynamic tool access control for AI agents based on user roles and permissions",
        tags: ["Security", "n8n", "Slack", "AI"],
        logos: ["n8n", "Slack"],
        link: "/guides/all/implement-rbac-for-ai-agents-with-n8n-and-port",
    },
    {
        title: "Gain visibility into delivery performance",
        description: "Track engineering delivery performance using key metrics like PR cycle time, throughput, deployment frequency, and overdue PRs",
        tags: ["Engineering Intelligence", "GitHub", "Azure DevOps", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/measure-and-track-delivery-performance",
    },
    {
        title: "Measure delivery reliability and stability",
        description: "Measure reliability and stability of your delivery pipeline by tracking workflow failure rates and PRs blocked by failing CI/CD using Port's GitHub integration",
        tags: ["Engineering Intelligence", "GitHub", "Azure DevOps", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/measure-reliability-and-stability",
    },
    {
        title: 'Track standards adherence',
        description: "Learn how to track standards adherence across your software delivery, tracking quality, security, and organizational alignment using Port's GitHub integration and scorecards.",
        tags: ["Engineering Intelligence", "GitHub", "Azure DevOps", "Scorecards"],
        logos: ["GitHub"],
        link: "/guides/all/measure-standards",
    },
    {
        title: "Track AI adoption and impact",
        description: "Track AI adoption and impact across your engineering teams and assess the impact of AI usage on delivery metrics like PR throughput and cycle time",
        tags: ["Engineering Intelligence", "GitHub", "Dashboards"],
        logos: ["GitHub"],
        link: "/guides/all/track-ai-adoption-and-impact",
    },
    {
        title: "Visualize Cursor metrics",
        description: "Create dashboards to monitor Cursor AI usage, track adoption, analyze costs, and measure developer productivity",
        tags: ["Engineering Intelligence", "Dashboards", "AI"],
        logos: ["Cursor"],
        link: "/guides/all/visualize-cursor-metrics",
    },
    {
        title: "Visualize Claude metrics",
        description: "Create dashboards to monitor Claude API usage, track costs, analyze model performance, and measure workspace-level metrics",
        tags: ["Engineering Intelligence", "Dashboards", "Claude Code"],
        logos: ["Claude Code"],
        link: "/guides/all/visualize-claude-metrics",
    },
    {
        title: "Ingest Claude Code security reviews",
        description: "Ingest Claude Code security reviews into Port using Port's GitHub file ingesting feature",
        tags: ["Security", "Claude Code", "GitHub"],
        logos: ["Claude Code", "GitHub"],
        link: "/guides/all/ingest-claude-code-security-reviews",
    },
    {
        title: "Auto-assign bugs to owners with ai",
        description: "Automatically assign Jira bugs to owning teams and services with Port automations and AI",
        tags: ["Agentic Work Management", "Jira", "AI", "Automations"],
        logos: ["Jira", "AI"],
        link: "/guides/all/auto-assign-bugs-to-owners",
    },
]

// Enhance guides with metadata (isNew property)
export const enhancedAvailableGuides = availableGuides.map(guide => ({
    ...guide,
    isNew: guideMetadata[guide.link]?.isNew || false
}));
