export const tagsCategoryMap = {
    "Use-cases": ["SDLC", "Incident management", "IaC", "Cloud access management", "Feature flag management", "AppSec", "Cloud cost", "K8s for devs", "Dev environments", "Engineering metrics"],
    "Port pillars": ["Actions", "Automations", "Dashboards", "Scorecards", "RBAC"],
    Technologies: [
        "Slack",
        "Terraform",
        "Jira",
        "SonarQube",
        "Kubernetes",
        "ArgoCD",
        "AWS",
        "Azure",
        "AzureDevops",
        "BitBucket",
        "GitHub",
        "GitLab",
        "GCP",
        "Jenkins",
        "Kubecost",
        "Launchdarkly",
        "Linear",
        "Opencost",
        "PagerDuty",
        "Snyk",
        "Datadog",
    ]
};

export const availableGuides = [
    {
        title: "Scaffold a new service",
        description: "Create a self-service action that scaffolds a new service",
        tags: ["SDLC", "Actions"],
        logos: ["SDLC"],
        category: "Getting started",
        link: "/guides/all/scaffold-a-new-service",
    },
    {
        title: "Ensure production readiness",
        description: "Define and track metrics for your services to ensure their production readiness",
        tags: ["Scorecards", "PagerDuty"],
        logos: ["SDLC", "PagerDuty"],
        category: "Getting started",
        link: "/guides/all/ensure-production-readiness",
    },
    {
        title: "Create cloud resources using IaC",
        description: "Create a self-service action that provisions cloud resources from a pre-defined template in your Git repository",
        tags: ["IaC", "AWS", "Actions", "Cloud access management"],
        logos: ["AWS", "SDLC"],
        category: "Getting started",
        link: "/guides/all/create-cloud-resource-using-iac",
    },
    {
        title: "Visualize your services' k8s runtime",
        description: "Create views to track the health, status, and other standards of your services' k8s runtime",
        tags: ["K8s for devs", "Actions", "Dashboards", "Scorecards"],
        logos: ["Kubernetes" ],
        category: "Getting started",
        link: "/guides/all/visualize-service-k8s-runtime",
    },
    {
        title: "Visualize your services' k8s runtime using ArgoCD",
        description: "Create views to track the health, status, and other standards of your services' k8s runtime using ArgoCD",
        tags: ["K8s for devs", "ArgoCD", "Actions", "Dashboards", "Scorecards"],
        logos: ["ArgoCD", "Kubernetes"],
        category: "Getting started",
        link: "/guides/all/visualize-service-argocd-runtime",
    },
    {
        title: "Enrich services using Gitops",
        description: "Empower developers to independently enrich their services using a self-service action",
        tags: ["SDLC", "Actions"],
        logos: ["SDLC"],
        category: "Getting started",
        link: "/guides/all/let-developers-enrich-services-using-gitops",
    },
    {
        title: "IAM permission management",
        description: "Empower developers to independently enrich their services using a self-service action",
        tags: ["Cloud access management", "Actions", "RBAC"],
        logos: ["AWS" ],
        category: "Getting started",
        link: "/guides/all/iam-permissions-guide",
    },
    {
        title: "Lock service deployment",
        description: "Implement a service locking mechanism using Port's GitHub Action",
        tags: ["SDLC", "Actions"],
        logos: ["SDLC", "GitHub"],
        category: "Getting started",
        link: "/guides/all/service-lock-github-workflow",
    },
    {
        title: "Slack reminders for scorecards",
        description: "Send a Slack reminder for uncompleted scorecard rules using a self-service action",
        tags: ["Engineering metrics", "Actions", "Scorecards"],
        logos: ["Slack"],
        category: "Getting started",
        link: "/guides/all/setup-slack-reminders",
    },
    {
        title: "Automate Slack alerts for old PRs",
        description: "Send a Slack notification for pull requests that have been open longer than a specified time using an automation",
        tags: ["SDLC", "Automations"],
        logos: ["Slack"],
        category: "Getting started",
        link: "/guides/all/automated-slack-alert-for-old-prs",
    },
    {
        title: "Manage resources using Kubernetes CRDs",
        description: "Integrate Kubernetes CRDs with Port and expose them in the Port UI for developers to use",
        tags: ["K8s for devs", "Actions"],
        logos: ["Kubernetes"],
        category: "Getting started",
        link: "/guides/all/manage-resources-using-k8s-crds",
    },
    {
        title: "Automate incident management",
        description: "Automate notifications and documentation of incidents",
        tags: ["Incident management", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        category: "Getting started",
        link: "/guides/all/create-slack-channel-for-reported-incident",
    },
    {
        title: "Resolve PagerDuty incidents",
        description: "Create a self-service action to resolve incidents and notify stakeholders",
        tags: ["Incident management", "Automations"],
        logos: ["PagerDuty", "GitHub"],
        category: "Getting started",
        link: "/guides/all/resolve-pagerduty-incident",
    },
    {
        title: "Connect GitHub repo (service) to a SonarQube project",
        description: "Create a logical connection between your services and their corresponding SonarQube projects",
        tags: ["AppSec", "SonarQube", "GitHub"],
        logos: ["SonarQube", "GitHub"],
        category: "Getting started",
        link: "/guides/all/connect-github-repository-with-sonarqube-project",
    },
    {
        title: "Connect GitHub Pull Request with Jira Issue",
        description: "Create a logical connection between your GitHub PRs and their corresponding Jira issues",
        tags: ["SDLC", "Jira", "GitHub"],
        logos: ["Jira", "GitHub"],
        category: "Getting started",
        link: "/guides/all/connect-github-pr-with-jira-issue",
    },
    {
        title: "Connect Jira issue to a service",
        description: "Create a logical connection between your Jira issues and their corresponding services",
        tags: ["SDLC", "Jira"],
        logos: ["Jira", "SDLC"],
        category: "Getting started",
        link: "/guides/all/connect-jira-issue-to-service",
    },

]

